### PR TITLE
Upgrade to upstream version 18.0.4

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *The application is not up-to-date with the upstream*

## Solution
- *Upgrade to latest version 18.0.4*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR297/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Package check ok for me.

**Comment by JimboJoe** [comment]
> Package check ok for me.

I also had checked the box :wink: 
Can be merged in 3 days.

**Comment by maniackcrudelis** [comment]
> I also had checked the box wink

Like I didn't read the PR before starting a test !?
Nooo I wouldn't even dare...

**Comment by lapineige** [comment]
It's been 3 days :)

**Pull request merged**
