### PR TITLE
opcache.interned_strings_buffer higher 8

### PR DESCRIPTION
**Pull request by pp-r**
Because I got a warning about it in the Nextcloud settings. The recommendation should be higher than 8 so randomly i've put 10, restart php-fpm and no more warning.

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by pp-r** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by OniriCorpe** [comment]
maybe increase it to 16 Mb to gain some margin?

**Comment by zamentur** [comment]
Finally 16Mb is not enough... On 32GB server i have a setup that put the same warning with 16MB...

**Comment by ericgaspar** [comment]
shall we increase the value to 32?

**Comment by lapineige** [comment]
@zamentur you might 32bits ?

**Comment by OniriCorpe** [comment]
> @zamentur you might 32bits ?

a server with 32GB of RAM i guess

**Comment by zamentur** [comment]
> a server with 32GB of RAM i guess

Yes sorry to not be accurate: a 32GB ram server

Here an answer from [MichaIng](https://help.nextcloud.com/u/MichaIng) that could help us to understand how this warning is triggered:
https://help.nextcloud.com/t/nextcloud-23-02-opcache-interned-strings-buffer/134007/5

So there is no good answer cause it depends of :
 *  nextcloud apps installed
 * eventually memory leak on one of those apps
 * (maybe) on other php apps (but i am not sure cause we are in separate pool)

**Pull request merged**
