### PR TITLE
Upgrade to version 20.0.8

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
## Problem
- A new minor upgrade to Nextcloud (20.0.8) was released

## Solution
- Upgrade to the newest version
## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
Thank you for this PR!

(the `!testme` command works for members of the YunoHost-Apps group)

**Comment by kay0u** [comment]
ha yes... you are a good bot @yunohost-bot

**Comment by ericgaspar** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
