### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Existing applications not in Nextcloud base archive are not kept after upgrade* #124
- *There are numerous apps sub-directories in the apps directory (see #123)* #124
- *There's often problems with /tmp too small and blocking the upgrade of Nextcloud* #127 
- *This application is "mostly" compatible with multi-instance, let's test and complete that!* #130 
- *Application is not up-to-date with upstream* #132 

## Solution
- *Correctly copy existing apps in the new Nextcloud apps directory during upgrade* #124
- *Use a temporary directory in /var/www instead of /tmp since when /tmp is too small is generally because of an old YunoHost iso.* #127 
- *Fix a remaining bug and activate multi-instance in manifest and check_process* #130 
- *Upgrade to latest version 13.0.5* #132 

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365 
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20testing%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready to be reviewed

**Comment by Josue-T** [comment]
Let's merge in 3 days

**Comment by JimboJoe** [comment]
Hm, doesn't look like #127 made it to this PR... :innocent:

**Comment by maniackcrudelis** [comment]
Right... We have the commit, but not the modifications.
Probably my revert...

Anyway, seems that this PR was not resolved yet. And it could be good to go further on this matter by the way !

**Pull request merged**
