### PR TITLE
last release for oldsatble 28.*

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *version 28.0.6 is oudated*

## Solution

- *upgrade olsdstable version 28 to last version 28.0.10*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by rodinux** [comment]
well I don't know why in bookworm CI upgrade from same version fails on this step...

> 2024-09-13 13:15:12,121: DEBUG - + sudo -u nextcloud php8.2 --define apc.enable_cli=1 occ --no-interaction --no-ansi app:update --all
> 2024-09-13 13:15:12,484: DEBUG - 
> 2024-09-13 13:15:12,487: WARNING - In RedisFactory.php line 123:

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
@zamentur do you think is a good idea upgrade your branch to last release 28 ?

**Comment by rodinux** [comment]
!testme

**Comment by ericgaspar** [comment]
superseded by [38a5832](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/658/commits/38a5832f2e238c7c90addd12ec4b84716c89e0ae)

**Pull request closed without merging**
