### PR TITLE
23.0.7

### LINKED ISSUE #473: Unable to access settings
I use YunoHost on a computer at home as a server, after installing Nextcloud, impossible to access the config-panel of the application from the administrator interface. I got an error message regarding: Control panel versions '0.1' are not supported.

YunoHost version is: 4.3.6.2 (stable)
Nextcloud version is: 22.2.3~ynh1

Capture d’écran (4)

### PR DESCRIPTION
**Pull request by ericgaspar**
## Changes

- https://github.com/YunoHost-Apps/nextcloud_ynh/pull/460
    - (this implies php 8.0)
- Upgrade config panel

Closes #473

### CODE REVIEW

**Comment by ericgaspar** [comment]
!bullseyetestme

**Comment by ericgaspar** [comment]
!bullseyetestme

**Comment by lapineige** [comment]
It sounds like it's ready for merging ?

**Comment by ericgaspar** [comment]
!testme

**Review by JimboJoe — APPROVED** [review]
LGTM 👍

**Review by alexAubin — APPROVED** [review]
LGTM :+1:

**Pull request merged**
