### PR TITLE
Upgrade to upstream version 14.0.4

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *This package isn't (at all) up-to-date with upstream*

## Solution
- *Upgrade to latest stable version*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [X] **Code review** : frju365
- [X] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : Josue
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20enh_version_14.0.4%20(Official)/)

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by frju365** [comment]
Well, I approved but I've a question : the referrer policy may be too strict for application which needs to communicate with other domains like collabora ? (don't know hpw it works for collabora... :/)

**Comment by frju365** [comment]
Anyway, if nothing is against it will be merged in testing in 3 days !

**Comment by alexAubin** [comment]
Bump @frju365 :wink:

**Comment by frju365** [comment]
oups... time to merge :)

**Pull request merged**
