### PR TITLE
Fix impossible upload via web interface and various warnings

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- Impossible upload via web interface
- various warnings reported on the forum

## Solution
- Fix impossible upload via web interface 
- Fix OPcache warnings
- Fix PATH warning
- Fix always_populate_raw_post_data warning

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR188/) 
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Comment by alexAubin** [comment]
Meh :| 

Is there any way that we could speed up the merging of this in stable é_è

I'm giving a workshop with 15+ people this weekend (tomorrow at 10 am) where I explain explicitly how to install Nextcloud and it's kinda disappointing if they just end up with "Not enough disk space" :/. Would be nice if I can avoid explaining to people "uh yea we have a fix for this but you can't have it" :/ 

Also considering all of the other "normal" people who will install YunoHost and Nextcloud considering it's the most popular app :/

**Comment by kay0u** [comment]
I'm not against to merge it into master like #186

Some people on support complain about this issue, and this looks to fix it well.

**Comment by frju365** [comment]
Same point of as @alexAubin and @kay0u. @JimboJoe : Is it ok to merge it now... as it's a _very needed_ fix ? Moreover, we have testing step... where we can attract some users to test the fix and have feedback quickly !

**Comment by alexAubin** [comment]
Soooo c.f. https://github.com/YunoHost-Apps/nextcloud_ynh/compare/c16a568799ba...a35a2457ce46

Discussed and agreed with @maniackcrudelis , sorry for the commit to master outside regular procedure, I need this for this morning :sob:

**Pull request merged**
