### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Version 15 is not supported anymore.*
- *The onlyoffice builtin feature in 18 is very useful.*
- *Install fails on buster because there's no php-mcrypt anymore*

## Solution
- *Add some php dependencies as suggested in https://docs.nextcloud.com/server/18/admin_manual/installation/source_installation.html to make some features working*
- Fix https://github.com/YunoHost-Apps/nextcloud_ynh/issues/257 https://github.com/YunoHost-Apps/nextcloud_ynh/issues/256 https://github.com/YunoHost-Apps/nextcloud_ynh/issues/205
- *Use php7.3*
- *Fix php issues with php7.4*
- *Fix the memory limit*
- *Fix detection of another caldav/carddav server*
- *Upgrade to last 18.0.2*

After a quick lookup on the internet, my understanding is that the stuff provided by php-mcrypt is old / deprecated since a while, and in fact Nextcloud doesnt need it anymore (it was added back to the jessie or maybe even squeeze era).

So let's remove it. (N.B. : I haven't tested anything though - but it should be okay to commit this for stretch as well)

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR260/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Do we add #259 as well?

**Comment by maniackcrudelis** [comment]
Missed that one
I resolve the conflict and I merge.
Could you update the first topic here meanwhile please ;)

**Comment by maniackcrudelis** [comment]
It was already done here https://github.com/YunoHost-Apps/nextcloud_ynh/pull/260/commits/c864e086625363d91dde6ba78a652011a991a027

**Comment by maniackcrudelis** [comment]
We will be lucky if there's no regression with that testing...

**Comment by JimboJoe** [comment]
FYI I'm going to open a 18.0.2 update on a separate branch.

**Comment by maniackcrudelis** [comment]
@zamentur please update the forum and this pull request accordingly to the pull request you just merged.

**Comment by zamentur** [comment]
Hi,
I am running a nextcloud  with this package exactly for 50 persons and tomorrow for 200 persons.

I had to tune some options like number of worker in nginx and number of simultaneous request (number of process) in php-fpm.

All things seems fine except the inherited permissions view feature which seems broken, could be a problem from upstream.

**Comment by lapineige** [comment]
I can't upgrade: if I do it manually using `yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh` it takes no time and at the end I'm still using 15.0.14.
I'm on Debian Jessie. Is this available only for Buster ?

**Comment by kay0u** [comment]
> I can't upgrade: if I do it manually using `yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh` it takes no time and at the end I'm still using 15.0.14.

```
sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing
```
with __/tree/testing__ at the end

**Comment by lapineige** [comment]
It is not supposed to be the default branch used now ? ^^

I did it, and… OHAY, it worked !  :tada: Nextcloud 18.0.2 installed, from 15.0.14 ! :tada: :balloon:

Great work everyone !

**Comment by lapineige** [comment]
I have only one issue: in `domain.tld/index.php/settings/admin/overview`, I have this message:
> La base de données a quelques index manquant. L'ajout d'index dans de grandes tables peut prendre un certain temps. Elles ne sont donc pas ajoutées automatiquement. En exécutant "occ db:add-missing-indices", ces index manquants pourront être ajoutés manuellement pendant que l'instance continue de tourner. Une fois les index ajoutés, les requêtes sur ces tables sont généralement beaucoup plus rapides.

I tried the command, but the command result was : 
> This version of Nextcloud requires at least PHP 7.2<br/>You are currently running 7.0.33-25+0~20200225.32+debian9~1.gbpa11893. Please update your PHP version

For the record, the command should be `sudo -u nextcloud php7.3 occ db:add-missing-indices`. And it worked :)

**Comment by maniackcrudelis** [comment]
The command about to be executed 10 minutes after your upgrade.
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/scripts/upgrade.d/upgrade.last.sh#L15

**Comment by lapineige** [comment]
Well, that's great if it was planned ^^ - I suppose it will create no issue ?

**Comment by lapineige** [comment]
Maybe it's an off-topic question : for those we are using this Nextcloud 18, does OnlyOffice works for you ?
I can't find a way to activate the integration in Nextcloud 18. Is Yunohost version supporting it ?

**Comment by kay0u** [comment]
Not working on arm arch, but if you are in x86/x86_64: https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/

**Comment by maniackcrudelis** [comment]
Guys, do you realize that we were supposed to declare this testing ready to be reviewed today, after 7 days of testing, and you did merge commits in the meantime without advertising the community, nor updating that very PR.

So, first, update when you add commits, tell people as well.
And, I extend this testing for 3 more days to have feedback on those new commits. (3 days considering the commits will be added to the forum and this PR today...)

**Comment by lapineige** [comment]
Regarding OnlyOffice integration: should we add more information about it (link to a tutorial, information about ARM support...) in the readme/forum ?
I guess it's expected by a lot of users who might be confused if it doesn't work out-of-the-box (additionally that would mean a lot of support work "for nothing") without further information.

**Comment by lapineige** [comment]
Upgrade tested again, this time again from 15.0.14 -> 18, but on a Rasberry Pi 3 (so ARM platform).
Upgrade went fine, everything seems to be ok, I only saw that error message:
> Process AsynchronousFileReader-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/moulinette/utils/stream.py", line 47, in run
    data += os.read(self._fd, 50)
OSError: [Errno 11] Resource temporarily unavailable

**Comment by maniackcrudelis** [comment]
Looks ok to me.

**Comment by lapineige** [comment]
And… it begins ! :D

**Pull request merged**
