### PR TITLE
Update install to avoid previewgenerator error

### PR DESCRIPTION
**Pull request by Bluesmoothie**
## Problem

https://github.com/nextcloud/previewgenerator/issues/154 when using

sudo -u nextcloud php8.1 /var/www/nextcloud/occ preview:generate-all -vvv

on a cronjob

## Solution

- Update install script to change home directory of nextcloud user

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [X] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Bluesmoothie** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
(Randomly passing by but this should be superseded by the packaging v2 PR, because the system_user resource reapplies the home dir every install/upgrade)

**Comment by ericgaspar** [comment]
Closing with #622

**Pull request closed without merging**
