### PR TITLE
Upgrade to upstream version 12.0.4 (fixes #75)

### LINKED ISSUE #75: Update package to 12.0.4
Update is possible through command line but not available in the nextcloud admin panel.
`sudo -u nextcloud php /var/www/nextcloud/updater/updater.phar -vv`

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
Package not up-to-date with upstream version

## Solution
Upgrade to uptream version 12.0.4

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.  

## Validation
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20enh_update_12.0.4%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
There seems to be a bug with package_linter and the upgrade script (says it's missing `ynh_abort_if_errors`...)

**Comment by maniackcrudelis** [comment]
Code review OK, Upgrade OK.

**Comment by JimboJoe** [comment]
Are you OK to merge that one in 3 days?

**Comment by maniackcrudelis** [comment]
Let's go

**Pull request merged**
