### PR TITLE
26.0.2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by JimboJoe** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by JimboJoe** [comment]
The multi-instance regression looks identified upstream; see https://github.com/nextcloud/server/issues/37610
An upstream fix has been done (https://github.com/nextcloud/server/pull/37853), and should most probably be integrated in next upstream release.

**Comment by lapineige** [comment]
Should we wait for this one in that case ? Or can we block upgrade in that situation ?

**Comment by JimboJoe** [comment]
I personally see no reason to rush to release that one; 26.0.2 will come soon enough 😅

**Comment by lapineige** [comment]
And it's available here if needed :)

**Review by eldertek — APPROVED** [review]
Tested on my side ! Working

Upstream has been merged

**Comment by eldertek** [comment]
!testme

**Comment by lapineige** [comment]
@JimboJoe is it safe to try it on a single install ?

**Comment by JimboJoe** [comment]
It think it is. I personally did the upgrade on my production server.

**Comment by eldertek** [comment]
Same here

**Comment by lapineige** [comment]
Upgrade went fine.

**Comment by kay0u** [comment]
tested on my side, everything works like a charm

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
