### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- #384
- #564

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Upgraded successfully from 26.0.1.

**Review by tituspijean — COMMENTED** [review]
Upgrade went smoothly, though I had to download apps again (Calendar, Contacts, ...). Can you check on your end?

**Review by tituspijean — APPROVED** [review]
Upgrade went smoothly.

**Pull request merged**
