### PR TITLE
Update to 15.0.0

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Nextcloud isn't up to do date*

## Solution
- *Update to 15.0.0*
- *Fix https://github.com/YunoHost-Apps/nextcloud_ynh/issues/147*

Thanks to @nath5394 for his work

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR148%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
I have some adapted patches for CSP to submit, but I don't have the rights to push to @nath5394 repository... Is there a simple way or should I open a new PR...?

**Comment by nath5394** [comment]
Hello @JimboJoe I gave you rights to push to my fork, is it ok ?

**Comment by JimboJoe** [comment]
Unfortunately not...

**Comment by JimboJoe** [comment]
There's an error on CI tests when upgrade from an older version: problem to apply the patches... @maniackcrudelis what's your opinion? You had once fixed the problem by applying the patches only on the latest version, yet it seems to try to apply the patch when installing 14.0.0 first.

**Comment by maniackcrudelis** [comment]
Found !
That the `source` of [upgrade.last.sh](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/c3d725c45bc14c110419924d5a8c544c15527b7e/scripts/upgrade#L154) which load the script and execute all the commands in it. And so the cp for the patches...

Those [lines](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/c3d725c45bc14c110419924d5a8c544c15527b7e/scripts/upgrade.d/upgrade.last.sh#L9-L13) should be put in a function, inside this very script, and execute at the end of the loop for the previous upgrade. So, it would be [here](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/c3d725c45bc14c110419924d5a8c544c15527b7e/scripts/upgrade#L178).
I'll try to do it right now, if github allow me to do so.

**Comment by maniackcrudelis** [comment]
I've tested it, it works. But I can't commit on this PR.

Here my diff
```
diff --git a/scripts/upgrade b/scripts/upgrade
index 6c54ca5..ccf44d9 100755
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -176,6 +176,8 @@ do
     # then it's the last upgrade to do
     if [ "$major_version" -eq "$current_major_version" ]; then
       current_major_version=last
+      # Execute the commands, kept for the last upgrade.
+      last_upgrade_exec
     fi
 
     # Load the value for this version

diff --git a/scripts/upgrade.d/upgrade.last.sh b/scripts/upgrade.d/upgrade.last.sh
index 2bed20b..24ed3ff 100755
--- a/scripts/upgrade.d/upgrade.last.sh
+++ b/scripts/upgrade.d/upgrade.last.sh
@@ -6,8 +6,11 @@ next_version="15.0.0"
 # Nextcloud tarball checksum sha256
 nextcloud_source_sha256="5bb0c58171353da844019b64080c21078002a59ab956ab72adb958844a98eb78"
 
-# Patch nextcloud files only for the last version
-cp -a ../sources/patches_last_version/* ../sources/patches
+# These commands are separated and put in a function, so the 'source' won't execute them until we need them.
+last_upgrade_exec () {
+       # Patch nextcloud files only for the last version
+       cp -a ../sources/patches_last_version/* ../sources/patches
 
-# Execute post-upgrade operations later on
-(cd /tmp ; at now + 10 minutes <<< "(cd $final_path ; sudo -u nextcloud php occ db:add-missing-indices ; sudo -u nextcloud php occ db:convert-filecache-bigint -n) > /tmp/nextcloud_maintenance.log")                                                                                                                                                      
+       # Execute post-upgrade operations later on
+       (cd /tmp ; at now + 10 minutes <<< "(cd $final_path ; sudo -u nextcloud php occ db:add-missing-indices ; sudo -u nextcloud php occ db:convert-filecache-bigint -n) > /tmp/nextcloud_maintenance.log")                                                                                                                                               
+}
```

**Comment by JimboJoe** [comment]
Looks like it's ready for review! :clap:

**Comment by JimboJoe** [comment]
New Year, new major Nextcloud version...?
Some reviews will be greatly appreciated :blush:

**Comment by frju365** [comment]
Well, we need one review now :-)

**Comment by maniackcrudelis** [comment]
I can't approve technically because I created this PR, but there's no commit from me. So I do.
LGTM.

Can be merged in 3 days.

**Pull request merged**
