### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Solution

- *Upgrade to 21.0.2*
- *Disable HTTP encoding between nextcloud and nginx to fix ynh tile*
- *New permission system*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by SohKa** [comment]
I just tested the upgrade of my Nextcloud instance to this testing version, and it worked fine.

However, in the "Security & setup warnings", this new message appeared : 
```
Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it.
```

It can be solve by installing the package `libmagickcore-6.q16-6-extra`. This package should be added to the `pkg_dependencies` variable in the `_common.sh` script.

Should I create a new issue for this or can this package be added in this testing branch ?

**Comment by kay0u** [comment]
!testme

**Comment by alexAubin** [comment]
Sooooo let's merge ? :thinking: :eyes:

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
