### PR TITLE
Disable  CSPv3 nonces and allow YunoHost fonts data (fixes #26 missing YunoHost tile and #18 blank page)

### LINKED ISSUE #26: Missing YunoHost tile
The YunoHost tile is missing in this application.
Unfortunately, even after applying latest fixes for missing tiles (see [this bug](https://dev.yunohost.org/issues/285)), it still doesn't show up.
The root cause seems to be the CSP nonce rules implemented in Nextcloud 11, that prevent the `ynhpanel.js` to be loaded by the browser.
I see no fix/workaround at this time, unless creating a dedicated Nextcloud app that would link back to the YunoHost menu.

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problems
- Due to some unknown problem in the interaction between SSOwat and Nextcloud server authentication, CSP nonces are wrong when you log into Nextcloud from YunoHost portal for the first time (systematically reproduced in a browser private session). The Nextcloud page is hence almost totally blank and you have to refresh the page or click on the Nextcloud logo.
- Due to CSP protection, the YunoHost tile (inline Javascript) is blocked

## Solution
While it's not a totally satisfying solution, a somewhat acceptable workaround to these two problems is to:
- block CSP v3 features (hence nonces), but still allowing CSP v2 features
- allow for "data:" font sources (needed to load YunoHost tile fonts)

This is done via patching Nextcloud sources:
- `ContentSecurityPolicyNonceManager`: disable the CSPv3 browser compatibility detection (return false in every case)
- `EmptyContentSecurityPolicy`: add the "data:" argument in `font-src` default CSP rule.

Note: Do to this package upgrade design, this patch won't be applied if you have already installed Nextcloud 12. As this patch is no that critical at this stage (and maybe Nextcloud 12.0.1 will come soon?), I propose to keep this upgrade mechanism as-is for now.

## PR Status
Work finished.
Could be reviewed and tested.

## Validation

- [x] **Complete test** : rafi59, frju365
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : Maniack C

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
I tried an upgrade from the version 11. It works fine and we don't have the blank screen anymore.

**Comment by JimboJoe** [comment]
@frju365 Can you please check what you did in the PR summary...? :wink:

**Comment by JimboJoe** [comment]
Need only one complete test... Abiding to [new rules](https://github.com/YunoHost/project-organization/pull/54), @Rafi594 could pass theses tests :wink:

**Comment by JimboJoe** [comment]
Bump!
Anyone willing to make a small test to end this PR validation...?

**Comment by Rafi594** [comment]
Sorry I did not see this comment

Works fine on my production server and my virtual machine in testing and unstable

**Comment by JimboJoe** [comment]
Great, thanks!
So will be merged in 3 days 👍

**Comment by frju365** [comment]
I did a complete test too. Everything works fine ! :+1 Thanks !!

**Pull request merged**
