### PR TITLE
Switch to php 8.2

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- #594

## Solution

- Bump PHP to 8.2 as it's supported by upstream.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
Also current `testing` branch is half baked as it already provisions `php8.2-fpm`

**Comment by ericgaspar** [comment]
#596 branch has php8.2 implemented and it is waiting to be tested before being merged to testing.

**Comment by orhtej2** [comment]
@ericgaspar How can I help with testing?

**Comment by orhtej2** [comment]
Superseded by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/596

**Comment by ericgaspar** [comment]
> @ericgaspar How can I help with testing?

You can update Nextcloud using this branch next iteration

**Pull request closed without merging**
