### PR TITLE
Upgrade to upstream version 15.0.8

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Application is not up-to-date with latest 15.x version*

## Solution
- *Upgrade to version 15.0.8*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR207/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
I'm sure you would have an easy way to adapt the patch, this should be written in a txt file or a script (if possible) to be sure this could be done easily if not by you.

**Comment by kay0u** [comment]
Can be merged in 3 days

**Comment by JimboJoe** [comment]
Well, this would need to be documented somewhere at a upper level, because it's quite the same idea for every patch:
* when upgrading the version of the package, check if the current patches needs to be updates (you get "Hunk #n failed" in the install log)

For each failing patch:
* create a git clone of the upstream application
* checkout the tag corresponding to the version you point to in the package
* apply the current patch which is failing (`patch -p1 < file.patch`)
* look at the .rej file created, and edit the file which couldn't be patched successfully
* at this stage, you need to understand the upstream language, the patch code, and how to adapt it...
* when the code is OK, then do a `git diff > file.patch`
* then test again the package installation

So unfortunately, no script will make it automatically...

Another option for git fans would be to create patch-specific branches in the upstream repository, commit the patch, use git format-patch, and git rebase for each new need of adaptation, bu I guess the learning curve will be steeper for newcomers...

**Comment by maniackcrudelis** [comment]
Ok... I though it was easy...
But yep, a documentation would be great ;)

**Comment by lapineige** [comment]
In my case, the update fails, because of fail2ban service.
(but maybe it's the same error that a lot of people encounter, and not related to this update)

**Comment by kay0u** [comment]
I'm confused, can we merged it?

**Comment by lapineige** [comment]
:up:
To merge or not to merge ? :)

**Comment by JimboJoe** [comment]
Can be closed in favour of #214 (if reviewed shortly)

**Comment by kay0u** [comment]
Okay, I'm closing this PR, feel free to complain if you think it's a bad decision!

**Pull request closed without merging**
