### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Dependency not installed : LDAP plugin of PHP.*
- *Package not up-to-date with upstream version*
- *Upgrade from an old version fails because the patches can't be applicated.*

## Solution
- *Install missing dependencies "php-ldap" #71*
- *Upgrade to uptream version 13.0.1 #90 #101*
- *Move the patches and restore them at their real place only for the last upgrade. We can't expect that the patches can be applicated to all versions. And they don't have to. #99*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Josue-T
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready to be reviewed.

**Comment by alexAubin** [comment]
Any update on this ? I've seen several people getting broken nextcloud install with the current stable, in the sense that they can't login because of the missing php-ldap dependency as far as I undersand ? :confused: 

To me it sounds like the changes are overall minor, so I wouldn't find it shocking to yolomerge this.

**Comment by JimboJoe** [comment]
What needs to be reviewed as every single PR has been reviewed and the whole PR has been suject to a testing phase...?
I have been using it in production for several weeks now, without any flaw.
I totally agree to release that one :+1:

**Comment by maniackcrudelis** [comment]
Because we have here 3 PR merged in testing, I think it wouldn't be useless to check the code as it is now.
It would be mainly a code review, to be sure there no conflict in the resultant PR.

Concerning the upgrade test. Well, I've already too much things to do... but I would really like to add this test in the check_process of every official apps. So that we could get rid of this test manually.

**Comment by JimboJoe** [comment]
So I just made an extensive code review and I hereby confirm that I didn't see any conflict in here :wink:

**Comment by maniackcrudelis** [comment]
Can be merged in 3 days.

**Pull request merged**
