### PR TITLE
Upgrade to upstream version 13.0.5

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Application is not up-to-date with upstream*

## Solution
- *Upgrade to latest version 13.0.5*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20enh_update_13.0.5%20(Official)/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Code review OK

CI Ok, despite the result, linked to this fix https://github.com/YunoHost-Apps/nextcloud_ynh/pull/129 (which, by the way, need a last approval...)

**Comment by violoncelloch** [comment]
@Josue-T 3 days?

**Comment by Josue-T** [comment]
Look like the CI failed, does anybody know why ?

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/nextcloud_ynh/pull/132#issuecomment-407830041

**Pull request merged**
