### PR TITLE
Update nginx conf for nextcloud 20

### PR DESCRIPTION
**Pull request by kay0u**
## Solution
- *[Nginx conf](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html)*
- */!\ I'm a noobie with nginx conf, have adapted the official conf, but I had to replace `alias` to `root` which implies some changes*

I tested integrated riot and onyoffice, and it works like a charm.

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR354%20(Kay0u)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by yalh76 — DISMISSED** [review]
Quick review, LGTM

**Comment by kay0u** [comment]
Tested and working, We have to be very careful, because we can break a lot of apps with this PR :-)

**Comment by lapineige** [comment]
>  because we can break a lot of apps with this PR :-)

Why ? (nginx total noob here)

**Comment by kay0u** [comment]
Because I'm also a noob, and with this new config all the rules have been changed. So if I screwed something up, it can break nextcloud intances.

**Comment by lapineige** [comment]
Also it won't affect any user that changed manually its nginx config ?
Then maybe it will break a lot of instances too, not for the same reason… how can we deal with this ? Warn everyone in the forum/here ? Warn during upgrade ?

**Comment by kay0u** [comment]
For users who have manually modified their nginx config, the upgrade script will create a backup of the modified conf and replace it with the new one.

I just put this message as a reminder that we need an extra testing period to get a maximum of users feedback

**Comment by lapineige** [comment]
That's a good thing. I completely forgot that new mechanism, thanks for the reminder.

**Review by yalh76 — APPROVED** [review]
Not better than you for nginx configuration....

**Review by alexAubin — APPROVED** [review]
LGTM  ¯\\\_(ツ)_/¯

**Review by zamentur — APPROVED** [review]
LGTM (untested)

**Pull request merged**
