### PR TITLE
28.0.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
patchs seem to be broken... `ynh_die '--message=Unable to apply patches'`

**Comment by orhtej2** [comment]
```
/var/cache/yunohost/app_tmp_work_dirs/app_tgwoalk3/app_folder/sources/patches/app-00-add-logout_url-conf.patch
patch --strip=1
patching file core/Controller/LoginController.php
Hunk #1 FAILED at 119.
1 out of 1 hunk FAILED -- saving rejects to file core/Controller/LoginController.php.rej
```

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
