### PR TITLE
Fix patches for v28

### PR DESCRIPTION
**Pull request by lapineige**
## Problem

- https://github.com/nextcloud/server/blame/master/core/Controller/LoginController.php#L102

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Fix patch fixes the issue with LoginController.php

```
153105 INFO DEBUG - patching file core/Controller/LoginController.php
153105 INFO DEBUG - Hunk YunoHost-Apps#1 succeeded at 97 (offset -22 lines).
```

From https://ci-apps-dev.yunohost.org/ci/job/12038

**Comment by alexAubin** [comment]
(NB : randomly jumping in, but @zamentur was pointing the other day that it is less trivial than it looks, because during the upgrade from older major version, the current upgrade process tries to applies the "new" patch on old versions, which is likely to fail ... Somehow we should either *not* apply the patch until the latest version, or apply the old version of the patch ...)

**Comment by lapineige** [comment]
Uh, I already thought it was trivial to fix :laughing:

This is in the last-version folder, maybe it already handled ?

**Comment by lapineige** [comment]
> Alrighty! [Test Badge](https://ci-apps-dev.yunohost.org/ci/job/12040) [](https://ci-apps-dev.yunohost.org/ci/job/12040)

Here we go, patches fixed for install :tada:

**Comment by alexAubin** [comment]
Hmmyeah my bad it seems to already be handled since a long time :P https://github.com/YunoHost-Apps/nextcloud_ynh/blob/83ac399638fe44f7a50e9de51d4f8cdb4659333b/scripts/upgrade#L197

**Comment by lapineige** [comment]
Upgrades are working straight away in CI :tada:

I'll try manual upgrade from v27.

**Comment by lapineige** [comment]
Should we update test.toml to check also upgrade from v27 ?

**Comment by lapineige** [comment]
Change_url fails too but it seems to be a CI issue.

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
