### PR TITLE
[fix] Group and user are not associated

### PR DESCRIPTION
**Pull request by zamentur**
## Problem
In user panel, yunohost groups are empty and special eponym unique member group are listed.

## Solution
Change the LDAP conf. 
Only LDAP group with a memberUid will be displayed. 
Eponym group, doesn't contains memberUid... I don't find another way to filter this correctly.
Note: to do that i activate the ldapExperienceAdmin to allow to set manually groupfilter... But i think the user should not change this config.

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Gredin67** [comment]
Tested on a fresh install. By default I have two groups displayed:
- all_users
- admins
I then added a group adherent with one user inside in Yunohost and after a reboot of the VirtualBox it was added to Nextcloud with corresponding user. Same for a group without user, it is not added to Nextcloud.

**Comment by Gredin67** [comment]
package checked https://paste.yunohost.org/qagihovoku.sql

**Comment by Gredin67** [comment]
was this already merged/solved? Would be nice to have more integration between yunohost and nextcloud groups.

**Comment by h3ndrik** [comment]
I'm not a reviewer but I can confirm this is working on my server. Just updated 'ldap_group_filter' and 'ldap_group_member_assoc_attribute' in my mysql database and it's working as intended.

Perhaps you should skip the 'ldapExperiencedAdmin' flag. This doesn't contribute anything to the solution of this problem and is maybe disabled on purpose.

**Review by kay0u — APPROVED** [review]

**Pull request merged**
