### PR TITLE
22.2.9

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 22.2.9

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Nice CI result :D

**Comment by yalh76** [comment]
There are conflict with testing branch as I switch from master to testing branch

**Comment by ericgaspar** [comment]
22.2.9 should be merged directly to master (testing is to be merged to master after bullseye release)

**Comment by yalh76** [comment]
> 22.2.9 should be merged directly to master (testing is to be merged to master after bullseye release)

in that case maybe testing would be moved to a new branch waiting bullseye
and recreate a new testing

**Pull request closed without merging**
