### PR TITLE
Upgrade to v.20.0.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem
- *New version upstream*

## Solution
- *Upgrade to version 20.0.0*
- *Small typos*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR338%20(ericgaspar)/) 

```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      SUCCESS
Deleting from a sub path:        SUCCESS
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         SUCCESS
Installation in private mode:    Not evaluated.
Installation in public mode:     Not evaluated.
Multi-instance installations:    SUCCESS
Malformed path:                  Not evaluated.
Port already used:               Not evaluated.
Backup:                          SUCCESS
Restore:                         SUCCESS
Change URL:                      SUCCESS
Actions and config-panel:        Not evaluated.
```

### CODE REVIEW

**Comment by ericgaspar** [comment]
The `ldap:test-config` kills the install script...  (When I disable `ldap:test-config` the CI is happy again)
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/a03e25fac417e2e03e53ed3a7b7ed05185637360/scripts/install#L189-L191

**Comment by KvL159** [comment]
Quick test on my test server was OK !
2 small issues :
- Logout from Nextcloud was not working and brought me back to NC Dashboard
- Yunohost tile doesn't seem to show up

**Comment by JimboJoe** [comment]
That looks like the PHP patches to adapt... Did you get any "Hunk failed" in the installation log?

**Comment by KvL159** [comment]
I didn't see any "Hunk failed", no "failed" at all actually (I just rechecked the install log)

**Comment by kay0u** [comment]
The patches apply well now :smile:

**Comment by KvL159** [comment]
Tested on my server, all good :+1:

**Comment by nathanael-h** [comment]
Hello, how could I help for this PR being merged ? Maybe by testing it with this command : 
`sudo yunohost app upgrade nextcloud -u https://github.com/ericgaspar/nextcloud_ynh/tree/v.20.0 --debug`

**Comment by KvL159** [comment]
> Hello, how could I help for this PR being merged ? Maybe by testing it with this command :
> `sudo yunohost app upgrade nextcloud -u https://github.com/ericgaspar/nextcloud_ynh/tree/v.20.0 --debug`

Yes that's correct ! @nathanael-h 

Note that NC 20.0.1 was just released, it may be better to use this version @ericgaspar @kay0u 
https://github.com/nextcloud/server/releases/tag/v20.0.1

**Comment by kay0u** [comment]
I'll merge it into testing, then upgrade to 20.0.1

**Review by kay0u — APPROVED** [review]

**Pull request merged**
