### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- #692
- #698
- Update to 29.0.4
- #703
- #710

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by kay0u** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html#approaching-upgrades

> Nextcloud must be upgraded step by step:
>
>       Before you can upgrade to the next major release, Nextcloud upgrades to the latest point release.
>
>        Then run the upgrade again to upgrade to the next major release’s latest point release.
>
 >       You cannot skip major releases. Please re-run the upgrade until you have reached the highest available (or applicable) release.
>
>       Example: 18.0.5 -> 18.0.11 -> 19.0.5 -> 20.0.2
>
> Wait for background migrations to finish after major upgrades. After upgrading to a new major version, some migrations are scheduled to run as a background job. If you plan to upgrade directly to another major version (e.g. 24 -> 25 -> 26) you need to make sure these migrations were executed before starting the next upgrade. To do so you should run the cron.php file 2-3 times, for example:
>
> ```
>$ sudo -u www-data php -f /var/www/nextcloud/cron.php
>```

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
we need to wait the next YunoHost release: https://github.com/YunoHost/yunohost/pull/1921

But this PR is ready to merge I think

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Review by kay0u — APPROVED** [review]
Ready to merge

**Pull request merged**
