### PR TITLE
Update install to fix localhost in notification

### PR DESCRIPTION
**Pull request by Mickael-Martin**
## Problem
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/17

## Solution
change overwrite.cli.url value

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR162%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Thanks for your PR!
Could you possibly rebase your branch on the latest testing so that we get a clearer view?

**Comment by Mickael-Martin** [comment]
sorry, but I don't understand exactly what you want :
I rebase my testing branch or my stable branch ? Or another (new) branch ?

**Comment by JimboJoe** [comment]
Sorry if I was unclear, I was advising to rebase (in the git definition) to the app's testing branch current state to get only one commit in the PR. In the current PR status, I think it would be probably better to start from scratch to get a clear situation :-)

**Comment by Mickael-Martin** [comment]
I have made a new tree since the master https://github.com/Mickael-Martin/nextcloud_ynh/tree/notify-fix. Would you want a new PR ?

**Comment by JimboJoe** [comment]
Yes, that could prove useful, but could you please create your branch off the testing branch and to the testing branch? Otherwise there are interfering commits.
Thanks!

**Comment by Mickael-Martin** [comment]
I close it, I reopen this PR via https://github.com/YunoHost-Apps/nextcloud_ynh/pull/175 on the right branch

**Pull request closed without merging**
