### PR TITLE
29.0.0

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 29.0.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by zamentur** [comment]
Note for now nextcloud tasks apps is not compatible with 29.0.0.

**Comment by nicofrand** [comment]
My 2 cents since I could not wait :stuck_out_tongue: : upgrade first failed due to a Nextcloud app (rightclick, deprecated since version 28 anyway), restore worked just fine. I removed the failing app and retried: everything worked like a charm :partying_face:

**Comment by lapineige** [comment]
> Note for now nextcloud tasks apps is not compatible with 29.0.0.

Fixed : https://github.com/nextcloud/tasks/issues/2536#issuecomment-2101315258

**Comment by ericgaspar** [comment]
!testme

**Review by kay0u — APPROVED** [review]

**Pull request merged**
