### PR TITLE
Update to php8.1

### PR DESCRIPTION
**Pull request by ericgaspar**
- Update to PHP8.1 as recommanded in [25.0.2 release](https://nextcloud.com/fr/blog/maintenance-releases-25-0-2-24-0-8-and-23-0-12-are-out/)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Well, it's announced during the installation... If you have a 32-bit Raspberry Pi you can't miss it 😬

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Pull request merged**
