### PR TITLE
Upgrade to 17.0.0

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Need php 7.1*

## Solution
- *Nextcloud 17.0.0*
- *Install php 7.1*

DONT TRY THAT AT HOME!

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR229/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by arthurlogilab** [comment]
We'd be interested in this being merged or being usable on a branch. Any reason this has stalled ? Is it waiting for yunohost on buster so that 7.1 doesn't need to be installed from sury ?

**Comment by arthurlogilab** [comment]
Upgrade from 15.x fails for us. Since the nextcloud was not yet used, we did a remove then install from scratch, which seems to be working.

**Comment by kay0u** [comment]
The upgrade should be fixed.

We don't really want to merge this PR because we don't want multiple version of php. Buster will provide new versions and the upgrade to 17.0.0 should be much easier.

I've make this PR just for people how want absolutely the latest version, but we don't provide any real support on these versions yet :-)

**Comment by MathieuDebit** [comment]
Thank you for this effort! ✨ Do you see any usability or security issues with this?

**Comment by kay0u** [comment]
It's not well tested, not well supported, the upgrade still fails (a simple `mkdir /etc/php/7.1/fpm/pool.d/ -p` before the upgrade should fix it but I haven't tested this workaround), I strongly discourage people from using multiple versions of php for YNH health, but when I proposed this upgrade nextcloud was working well and there's no reason to have more security problems with this version than with the stable.

**Comment by lapineige** [comment]
If we already have php7.0/7.2/7.3 installed, does another php version install is needed ?

**Comment by MathieuDebit** [comment]
> https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Nextcloud 15 will reach EOL 2019-12
Nextcloud 17 will reach EOL 2020-09
Nextcloud 18 will reach EOL 2021-01

Which means that if we want to be peaceful for the year 2020, could we already prepare the work for Nextcloud 18?

**Comment by lapineige** [comment]
First of all, what does EOL imply ? End of security fixes ?

And well, does Nextcloud 18 requires a new PHP version that won't be supported by the current Debian stable ? If it not the case, we'll see later, it's not a big deal to upgrade to Nextcloud 18 from 17, as it was for Nextcloud 15 after 14 and 13.

**Comment by nathanael-h** [comment]
Hello @kay0u thanks for this PR. Do you think I can try to update my nextcloud 15 to 17 with this branch ? I am a medium/advanced ynh admin :wink:  so I could manually fix some stuffs if something broke.

**Comment by kay0u** [comment]
> Hello @kay0u thanks for this PR. Do you think I can try to update my nextcloud 15 to 17 with this branch ? I am a medium/advanced ynh admin wink so I could manually fix some stuffs if something broke.

Hi! The upgrade still [fails](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR229/10/console) and I have no such time to put on this PR for now

**Pull request merged**
