### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Application is not up-to-date*

## Solution
- *Upgrade to latest version 15.0.10*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR216/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
@JimboJoe There is the version 15.0.10, but I still don't undersand how you create the `.patch` :smile:

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Comment by JimboJoe** [comment]
Following the recent new merge, needs another round of review @YunoHost-Apps/apps-group

**Comment by kay0u** [comment]
Need one LGTM :-)

**Comment by mediaformat** [comment]
reviewers please!

**Pull request merged**
