### PR TITLE
22.1.1

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 22.1.1

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
I do not know what happened with the CI, but the badge in the comment above is correct: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/423#issuecomment-893324927

**Comment by ericgaspar** [comment]
This PR https://github.com/YunoHost/yunohost/pull/1284 should help Nextcloud to  install successfully. (I don't know when this will be propagated to CI)

**Comment by lapineige** [comment]
This PR is also solving a security issue: https://forum.yunohost.org/t/security-vulnerabilites-dans-nextcloud/17077

**Comment by kay0u** [comment]
!testme

**Review by zamentur — APPROVED** [review]

**Pull request merged**
