### PR TITLE
Update nginx.conf

### PR DESCRIPTION
**Pull request by Thatoo**
To make Gestion app work

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thatoo** [comment]
Would solve this issue : https://github.com/baimard/gestion/issues/360

**Comment by ericgaspar** [comment]
Is this related to the #628 PR?

**Comment by Thatoo** [comment]
Oh my god... I forgot I PR it already... I should go to sleep.

**Comment by ericgaspar** [comment]
I understand, the PR was merged very quickly, which is unusual for nextcloud PR

**Pull request closed without merging**
