### PR TITLE
26.0.11 (Oldstable)

### PR DESCRIPTION
**Pull request by zamentur**
## Problem

Need a branch of the repo with 26.0.11 for people who wants to stay a bit on 26 branch...

## Solution

Don't merge or delete this branch, i suggest to use it as a main branch.

### CODE REVIEW

**Comment by zamentur** [comment]
!testme

**Comment by lapineige** [comment]
It might be very important for the people locked on 32-bits architecture.

**Comment by alexAubin** [comment]
(Do you mean 26.x is the last supported version for 32 bit arch ? I thought Nextcloud somehow reconsidered their decisions and were not going to drop 32 bit support before a while ? Or maybe I missed some new part of the story :grimacing: )

**Comment by lapineige** [comment]
That is right : they announced they will try to continue to support 32 bit.
But we don't know for how long, and in v26 (should be fixed in the last minor releases) and v27 there were regression specific to the 32 bit architecture, that took a while to be fixed.
So having the hotfix backported to v26 in Yunohost is great for such situations :)

**Comment by tomdereub** [comment]
Hi, it would be grate to get 26.0.6 on this branch, if someone could do that.

**Comment by ericgaspar** [comment]
!testme

**Comment by tomdereub** [comment]
Hi, thanks a lot, is it already ready to upgrade ?

**Comment by ericgaspar** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
