### PR TITLE
Upgrade to version 21.0.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem
- *New version upstream*

## Solution
- *Upgrade to version 21.0.0*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
I made the upgrade on my server... some warnings showing in `Avertissements de sécurité & configuration `:
```
- Une tâche en arrière-plan qui vérifie les certificats SSL importés par l’utilisateur est en attente. Veuillez vérifier plus tard.

- La configuration du serveur web ne permet pas d'atteindre "/.well-known/webfinger". Vous trouverez plus d'informations dans la documentation.

- La configuration du serveur web ne permet pas d'atteindre "/.well-known/nodeinfo". Vous trouverez plus d'informations dans la documentation.

- Votre installation n’a pas de préfixe de région par défaut. C’est nécessaire pour valider les numéros de téléphone dans les paramètres du profil sans code pays. Pour autoriser les numéros sans code pays, veuillez ajouter "default_phone_region" avec le code ISO 3166-1 respectif de la région dans votre fichier de configuration.
```

**Comment by Bugsbane** [comment]
Does this install the new high performance backend?

**Comment by kay0u** [comment]
> Does this install the new high performance backend?

Are you talking about https://github.com/nextcloud/notify_push ?

The install fails on my dev install.

**Review by kay0u — DISMISSED** [review]
:+1:

**Comment by ericgaspar** [comment]
!testme

**Review by kay0u — DISMISSED** [review]

**Review by kay0u — APPROVED** [review]

**Pull request merged**
