### PR TITLE
Enable Redis file locking

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- Gallery plugin doesn't work for accounts containing many files (timeout)
- Optimize global performance

## Solution
- Add ImageMagick dependency and tune timeouts for Gallery plugin
- For optimization reason, and as Redis is already running on a YunoHost instance, setup Nextcloud to use it by default (see documentation [here](https://docs.nextcloud.com/server/12.0/admin_manual/configuration_server/caching_configuration.html#small-organization-single-server-setup) and recommendation for Gallery plugin [here](https://github.com/nextcloud/gallery/wiki/Requirements#recommended)).
## PR Status

Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [ ] **Approval (LGTM)** : 
- [x] **Approval (LGTM)** : Maniack C
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20enh_redis_locking%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
All ok

**Comment by JimboJoe** [comment]
Can we merge this in 3 days... ?
Another tester, like @Rafi594 ... ?

**Comment by maniackcrudelis** [comment]
Should we really wait more ?

**Comment by JimboJoe** [comment]
Nope, 23 days seem enough 😄

**Pull request merged**
