### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
* Refactoring: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/59
* Nextcloud 12.0.3: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/64
* Nextcloud 12.0.4: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/76

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
There's an issue with this testing, https://github.com/YunoHost-Apps/nextcloud_ynh/pull/72

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/nextcloud_ynh/pull/72 merged.

**Comment by maniackcrudelis** [comment]
Should we wait for https://github.com/YunoHost-Apps/nextcloud_ynh/pull/77 and https://github.com/YunoHost-Apps/nextcloud_ynh/pull/76 ?

**Comment by JimboJoe** [comment]
Maybe #76, provided we merge it in 3 days.
Maybe not #77 as it needs reviews.

**Comment by maniackcrudelis** [comment]
That's exactly what I hoped to read ;)

**Comment by JimboJoe** [comment]
#76 now merged, but #77 not far from being reviewed...

**Comment by maniackcrudelis** [comment]
So ? merge in 3 days ?
Or we're waiting for https://github.com/YunoHost-Apps/nextcloud_ynh/pull/77 ?

**Pull request merged**
