### PR TITLE
Don't use parentheses

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Parentheses are useless here (I guess?)*
- *Parentheses create a subshell, and ynh_die exit only the subshell, not the main script*

## Solution
- *Remove parentheses*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR264/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
I'm sorry, can you please precise the rationale in the PR description... ? :innocent:

**Comment by kay0u** [comment]
Done :-)

**Comment by maniackcrudelis** [comment]
For sure the parenthesis break ynh_die, which will exit the sub shell only. But are you sure about the priority of the logical OR ?
Did you actually test the behavior of this ?

**Comment by kay0u** [comment]
I have to admit that I didn't test this code, but in bash leftmost operations are executed first

https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Lists

Anyway I'll run some tests

**Comment by kay0u** [comment]
Should we merge it in 3 days or when #260 is merged?

**Comment by maniackcrudelis** [comment]
That doesn't look like a hotfix, so I guess it can wait until the next release.

**Comment by alexAubin** [comment]
By next release you mean the current testing ? To me it *does* look like a kinda urgent thing to merge considering that if the exec_occ upgrade fails, the script will continue and it's likely to create a huge mess (though I didn't take a look at what happens next). So at least should be merged for the 18.x considering many people are going to upgrade ?

**Comment by maniackcrudelis** [comment]
Considering that error in the code is 4 years old, I don't think we should really consider it like a big issue !
This error appear in this https://github.com/YunoHost-Apps/nextcloud_ynh/commit/5cbd01ab57c8550ca6d60538ff87d55493d40a58#diff-44cb16c778719320333118c04d509a7cR98...

**Comment by kay0u** [comment]
On the other hand, since this is a fairly major upgrade, it would be best to fix any known issue to avoid a shit storm...

**Comment by lapineige** [comment]
I don't know the details and implications, but if it creates no major additional risk during the upgrade, I think too that it's good to merge that with the rest.
Also, people might not upgrade their Nextcloud so often (considering it's not a "simple" app, and as it broke a few time in the past, for my part I try to be cautious with its updates), and this would delay the fix maybe until the next major version maybe.

**Comment by maniackcrudelis** [comment]
To be honest, I don't use Nextcloud so much and my version 15 works pretty well for what I need to do.

But, I try to not postpone any more this release everyone seem to wait for.
So that I try to not include any new commit that are not really important.

Considering this code works since 4 years. I'm more worried about what will happen when merged than the opposite.

Still, there's 2 solutions, either we merge right now into testing and we'll see what happen in the next 3 days. In hope a regression wouldn't go unnoticed.
Or we merge in 3 days and postpone again the release of this testing.

Again, I won't probably jump on the occasion to upgrade my own nextcloud to 18. So, both solutions fit me. If you really don't want to wait for the next release of course.

**Comment by lapineige** [comment]
If it's a matter of 3 more days with a testing branch with this fix and a master branch with v18, maybe it's not a big deal (by the time people learn about the available upgrade + actually upgrade their instance). Yet that might mean a lot of upgrades, as v18 is much expected.
FYI I'm gonna test it right now.

**Pull request merged**
