### PR TITLE
Do not use argon2 to hash password

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Argon2, used to hashing password slow down small devices*
- *https://forum.yunohost.org/t/official-app-nextcloud/9223/148*

## Solution
- *According to https://github.com/nextcloud/server/pull/19203, do not use argon2 at all.*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR294/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
This setting will only be available in Nextcloud 19. I suppose it's harmless on Nextcloud 18... ?

**Comment by maniackcrudelis** [comment]
Apparently it already worked on 18. According to SilverViper on the forum.
Or was it just a placebo effect ?

**Comment by kay0u** [comment]
Has been backported: https://github.com/nextcloud/server/pull/19203#issuecomment-581843212

And it's present in `stable18` branch: https://github.com/nextcloud/server/blob/stable18/config/config.sample.php#L1445

**Comment by kay0u** [comment]
Can be merged in 3 days

**Comment by maniackcrudelis** [comment]
I was wondering where the CI test was...
Forgot that this app is not official nor High quality anymore...

**Pull request merged**
