### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Uncaught error during upgrade*
- *Caldav/Calddav broken during upgrade*
- *Many users get stuck in maintenance mode, and have to go to ssh to fix it*
- *Application not up-to-date with the upstream*
- *Multi instance fails because the nginx conf file has multiple .well-known...*
- *Argon2, used to hashing password slow down small devices*

## Solution
- *Remove parentheses*
- *Reload nginx before to checking if .well-known is available for this domain*
- *Add an action to remove the maintenance mode from the admin panel.*
- *Upgrade to latest version 18.0.4*
- *Do not keep .well-known(s) into nginx without a proper check...*
- *Do not use argon2 to hash password*
- *Explain how to use occ command with Yunohost config*
- *Explain how to configure onlyoffice*
- *Add french readme*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR274/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
This testing haven't been advertised on the forum.
Are we waiting for other PR to be merged ? #272 #241 ?

**Comment by kay0u** [comment]
That was my idea before I announced it on the forum, at least #272

**Comment by lapineige** [comment]
What about adding #297 ?

**Comment by kay0u** [comment]
There are still https://github.com/YunoHost-Apps/nextcloud_ynh/pull/278 and https://github.com/YunoHost-Apps/nextcloud_ynh/pull/282 do we want to add them to the testing? (the current testing are quite big O.O.)

**Comment by lapineige** [comment]
Upgrade from 18.0.3 went fine :)

#278 is easy, it only changes the readme.
For #282 I don't know, was it tested enough ? At least merging or not won't change anything for the users targeted by this PR, so maybe we merge this testing first, and then test #282 ?

**Comment by maniackcrudelis** [comment]
I'm for merging #278 and wait for the next testing for #282, which is little bit trickier.

**Comment by lapineige** [comment]
Upgrade on an ARM server, from 18.0.3, went fine too :)

**Comment by Thatoo** [comment]
Is this PR ready to merge?

**Comment by maniackcrudelis** [comment]
Not yet I think, at least we're waiting for the PR about the doc.
And then, we'll have a look to the current status on the forum.

**Comment by lapineige** [comment]
I think we can advertise it already, as the readme part won't change anything on the users testing side.

**Comment by maniackcrudelis** [comment]
It was already a few days ago https://forum.yunohost.org/t/official-topic-nextcloud/9223/197

**Comment by lapineige** [comment]
@kay0u could you edit the first message to add the information about the French Readme + OnlyOffice doc ?

**Comment by lapineige** [comment]
I guess we can merge ?

**Comment by kay0u** [comment]
Ready for review?

**Comment by lapineige** [comment]
Ready to merge ? :) 🆙

**Comment by kay0u** [comment]
Merging in 3 days if nobody complains :-)

**Pull request merged**
