### PR TITLE
[fix] backup_core_only settings doesn't work

### PR DESCRIPTION
**Pull request by zamentur**
## Problem
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/79

## Solution
Apply the backup core only env var if present in settings and we aren not in upgrade mode

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR196/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by martoni35** [comment]
Nice job and check manually OK

**Comment by martoni35** [comment]
With the new changes "auto" to replace "default", it's OK for me :)

**Comment by maniackcrudelis** [comment]
This is not a bug...
Going back to the previous behavior isn't the right way to do it.

**Comment by JimboJoe** [comment]
I guess we can safely close that one, as there were no new reports linked with the change in backup parameter strategy...?

**Comment by kay0u** [comment]
I'm closing this PR, don't hesitate to reopen it if needed

**Pull request closed without merging**
