### PR TITLE
Upgrade to upstream version 13.0.0

### LINKED ISSUE #63: Upgrade to NextCloud 12.0.3
The new update is [available](https://nextcloud.com/blog/nextcloud-updates-12.0.3-11.0.5-are-here/)!

### PR DESCRIPTION
**Pull request by frju365**
## Problem
Package not up-to-date with upstream version

## Solution
Upgrade to uptream version 13.0.0

## PR Status
Could be reviewed and tested.  
fix #63 

## Validation
- [x] **Upgrade previous version** :  Rafi594, Maniack C
- [x] **Code review** : Rafi594, Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%2013RC-upgrade%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by frju365** [comment]
yes, In fact, it's not finished yet. I work at University for instance. I will work on this this afternoon.

**Comment by frju365** [comment]
Is it better like that @Rafi594 ?

**Comment by frju365** [comment]
... no answer... I think it can be good to provide the latest version sooner as possible ;)

**Comment by Rafi594** [comment]
I will try the update since the old version tonight

frju365 <notifications@github.com> a écrit :

**Comment by frju365** [comment]
@JimboJoe : one LGTM ?

**Comment by JimboJoe** [comment]
Have you seen any impact on the nginx conf file linked to the nginx conf changes stated in the release notes here?
https://docs.nextcloud.com/server/13/admin_manual/release_notes.html#changes-in-nextcloud-version

**Comment by maniackcrudelis** [comment]
Are these modifications have been made somewhere else ?

**Comment by zamentur** [comment]
I have deployed it in production (current 12.0.5 doesn't work).

**Comment by frju365** [comment]
I have it in production too without any problem. Nginx is not really a problem in this PR... and not a security problem too. But I will see that tomorrow, if you insist :wink:

**Comment by frju365** [comment]
Moreover, I see 3 points : 
- gzip conf is in the main conf I haven't access. (perhaps you have an idea ?) and that's not a big change.
- X-FRAME-OPTION not found on my side.
- The use of http2 is not required in this conf too.

**Comment by frju365** [comment]
PING. (btw: I did this PR quickly as possible to update quickly the instance as the community wanted. :P )

**Comment by Rafi594** [comment]
X-FRAME-OPTION has already been removed when updating to Nextcloud 12 and http2 is not compatible with the version of nginx that is in Jessie.

Everything is good for me

**Comment by frju365** [comment]
ok 24 days. Too much for me. Let's merge the PR in 3 day if no more opposition.

**Comment by maniackcrudelis** [comment]
I was about to propose that :)
Don't forget to announce the testing in the forum post.

**Comment by JimboJoe** [comment]
LGTM as well 👍

**Comment by Rafi594** [comment]
Let's merge it !

**Pull request merged**
