### PR TITLE
testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Update Nextcloud to 27.1.1
-  Fix slow uploads under HTTP2  #602

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by Salamandar — APPROVED** [review]
LGTM. Gonna test on my server today.

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Pull request merged**
