### PR TITLE
Add fail2ban configuration (closes #39)

### LINKED ISSUE #39: Set fail2ban rules
In order to protect against brute-force attacks, fail2ban rules should ideally be set. There's an example [here](https://www.c-rieger.de/nextcloud-installation-guide/#c103) that can serve as guideline.

### PR DESCRIPTION
**Pull request by Rafi594**
## Problem
Nextcloud implements a brute-force attacks protection through slowing down further connections from backlisted IP addresses. The package could anyway also take advantage from fail2ban with straight (temporary) bans.

## Solution
- First proposal for a generalized helper to create/remove fail2ban configurations
- Use of this helper in this package

## PR Status
Work finished.
Could be reviewed and tested.

## Validation

- [ ] ~**Complete test** :~
- [ ] ~**Upgrade previous version** :~
- [ ] ~**Code review** :~
- [ ] ~**Approval (LGTM)** :~
- [ ] ~**Approval (LGTM)** :~
- [ ] ~**CI succeeded** :~

Since this PR has been rerouted from master to testing. It passes to a minor decision.
- [ ] **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20Add_fail2ban%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Thanks for this PR!
I didn't test it, but I think you need to restart the fail2ban service in order for it to take the configuration into account.
Moreover, you also need to take care of removal.

**Comment by JimboJoe** [comment]
Tested OK, with these warnings at install/remove : 
```
Warning: WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
Warning: WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
```
Can you possibly try using the helper I developed in [this PR](https://github.com/YunoHost-Apps/piwigo_ynh/pull/9)?
Thanks!

**Comment by Rafi594** [comment]
It's normal these warnings are already there without nextcloud

I will try the helpers

18 juin 2017 16:04 "JimboJoe"  a écrit:
	Tested OK, with these warnings at install/remove : 

	Warning: WARNING 'ignoreregex' not defined in 'Definition'. Using default one: '' Warning: WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''  

	Can you possibly try using the helper I developed in this PR (https://github.com/YunoHost-Apps/piwigo_ynh/pull/9)?
Thanks!

**Comment by JimboJoe** [comment]
I pushed some changes... You clearly hadn't tested your code ;-)

**Comment by Rafi594** [comment]
I tried on a virtual machine but no fail2ban filter is created I think 
it's because nextcloud has already a protection 
https://nextcloud.com/secure/ 
https://framapic.org/gSckBk2N4VOT/7G6NPlbjlK1x.png   (I use the testing 
version of yunohost)

**Comment by JimboJoe** [comment]
Did it create `/etc/fail2ban/jail.d/nextcloud.conf` and `/etc/fail2ban/filter.d.nextcloud.conf`? What does `/var/log/fail2ban.log` say?

It has little to do with Nextcloud integrated protection, but you're right Nextcloud brings bruteforce protection out-of-the-box: it brought it in [Nextcloud 11](https://nextcloud.com/blog/nextcloud-11-delivers-verified-security-improvements/) and reinforced it in [Nextcloud 12](https://nextcloud.com/blog/security-in-nextcloud-12-bruteforce-protection-and-rate-limiting-for-developers/). But in my opinion, they had to, because they wanted to avoid to ask their users to deploy additional software like fail2ban.

As for our situation, we have  fail2ban, and using it is:

- cheap,
- an even more radicale protection: we can eventually ban IP addresses.

@maniackcrudelis, what do you think?

**Comment by maniackcrudelis** [comment]
Sorry I missed that...

I agree with JimboJoe, we have fail2ban in YunoHost, and now, we have a helper to use it easier.
So, let's use it.

And, we should consider that nextcloud is a popular app, so as a popular app it become a target, whatever the security it brings.
So, adding fail2ban is really a good things to protect this app.

**Comment by anmol26s** [comment]
I have not tested it. But is this PR still legitimate?

**Comment by maniackcrudelis** [comment]
No as it is.
But, adding fail2ban to nextcloud would be really great.
This PR should be reworked to use the new helper for fail2ban.

**Comment by JimboJoe** [comment]
Obsoleted by #182

**Pull request closed without merging**
