### PR TITLE
Update check_process

### PR DESCRIPTION
**Pull request by ericgaspar**
- Set check process for config panel

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@alexAubin Are the new config-panels testable with package-check?

**Comment by kay0u** [comment]
Hmm I'd say no

**Comment by alexAubin** [comment]
Hmpf yeah package_check needs to be reworked to interface with the new config panel API ... And maybe we need to think what / how we want to test stuff exactly. For example it's quite boring to have to declare all that stuff in check_process. Also in the general case there are more complex panels than just single independent questions (c.f. for example vpnclient, hotspot) so it's not clear how to test those.

**Pull request closed without merging**
