### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *This application is not up-to-date*
- *Normalization from example_ynh*

## Solution
- *Upgrade to latest version 15.0.7*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR200/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Proposing to wait for #174 to get merged.

**Comment by JimboJoe** [comment]
Let's review and merge that one, so that we can have a testing with 15.0.8 (or 9).

**Comment by maniackcrudelis** [comment]
Code review OK, even if most of the code modifications are from me...

**Comment by kay0u** [comment]
Can be merged in 3 days

**Pull request merged**
