### PR TITLE
Fix Change PHP-FPM configuration 

### PR DESCRIPTION
**Pull request by grenagit**
## Problem

- *When the PHP-FPM configuration is changed in the control panel (Memory footprint or Expected usage), the PHP version (8.2) is not passed to `ynh_add_fpm_config`. The changes are therefore applied on the default PHP version (7.4) resulting in an error 500!*

## Solution

- *Add `YNH_PHP_VERSION=8.2` into `_common.sh` as indicated in [ynh_add_fpm_config](https://github.com/YunoHost/yunohost/blob/4897f72974fff30b168a40bf55bf917395cca4cc/helpers/php#L4-L6)*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by alexAubin** [comment]
Uuuuh but nowadays we use `$phpversion` which indeeds seems to be the one used in `scripts/config` so that doesnt seem to be the culprit ..?

**Comment by alexAubin** [comment]
Ah I see, the actual issue is probably that unlike the other scripts, the settings are not auto-loaded in the `scrips/config` context .. so we just need to load `phpversion`

**Comment by alexAubin** [comment]
Ah no, it *is* already loaded ... https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/scripts/config#L18 ... i'm super confused

**Comment by alexAubin** [comment]
@grenagit : if you are still able to reproduce this issue, it would be nice to have the full detailed log of the config panel apply operation to debug it

**Comment by snm247** [comment]
This issue just happened to me on a "normal" (i.e. no testing or debug) Nextcloud installation. Steps to reproduce:
* Install Nextcloud
* Check the php version:
* In the admin panel go to Applications > nextcloud > Nextcloud configuration
* Change the `expected usage` value e.g. from medium to low.

**Comment by snm247** [comment]
This issue just happened on my Nextcloud installation. Steps to reproduce:

* Install Nextcloud
* Check the php version: 
```
yunohost app setting nextcloud phpversion
8.2
```
* In the Admin panel go to Applications > nextcloud > Nextcloud configuration
* Change the `expected usage` value e.g. from medium to low and click save.
* Check the php version: 
```
yunohost app setting nextcloud phpversion
7.4
```

Log: https://paste.yunohost.org/raw/avaxitides

**Comment by alexAubin** [comment]
To be fixed by https://github.com/YunoHost/yunohost/commit/077b745d60de405d2250008adc254488796bb70f in upcoming yunohost 11.2.10

**Pull request closed without merging**
