### PR TITLE
New permissions system

### PR DESCRIPTION
**Pull request by kay0u**
## Solution
- *Use the new permissions system*

For now, when we change the permission from "all_users" to "visitors", we can't login anymore. It looks like a bug from the core side.

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR241/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Josue-T** [comment]
Hello,

Tried, nextcloud from the stable branch, I saw that to be able to see all group correctly we need to set the parameter `Association groupe-membre` to `member (AD)`.

**Comment by kay0u** [comment]
> [...] we need to set the parameter `Association groupe-membre` to `member (AD)`.

Uuh, where?

**Comment by maniackcrudelis** [comment]
We should probably wait for https://github.com/YunoHost/yunohost/pull/861 to have a clean and really working migration.

**Comment by Josue-T** [comment]
> > [...] we need to set the parameter `Association groupe-membre` to `member (AD)`.
> 
> Uuh, where?

I did it on the admin of nextcloud. But it should be probably possible to do this in CLI

Screenshot_20200501_160248

**Comment by kay0u** [comment]
!testme

**Pull request merged**
