### PR TITLE
Upgrade to upstream version 12.0.3

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
Package not up-to-date with upstream version

## Solution
Upgrade to uptream version 12.0.3

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.  

## Validation
- [x] **Upgrade previous version** : Rafi59
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : Maniack C
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20enh-nextcloud-12.0.3%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by Rafi594** [comment]
One more review needed !

**Comment by frju365** [comment]
Will be merged in 3 days !

**Comment by JimboJoe** [comment]
Maybe not...
@rafi59 stated on the chat room that login from portal wasn't working any more... is it for you?

**Comment by frju365** [comment]
Wait, ok. I will retest.

**Comment by maniackcrudelis** [comment]
I confirm there's an error...

{"reqId":"Eb3I50MdF3gO9ywbj7s2","level":3,"time":"2017-11-03T22:33:44+00:00","remoteAddr":"192.168.1.48","user":"mcrudelis","app":"index","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.3.3"}

And I suggest to activate this log ! Even if here it's not really helpful...
```
'log_type' => 'owncloud',
'logfile' => '/var/log/nextcloud.log',
'loglevel' => '2',
```
In the config file 'config/config.php'

**Comment by JimboJoe** [comment]
@maniackcrudelis Can't reproduce... What did you do in Nextcloud before getting this message?

What about the SSO login? @Rafi594 stated it wasn't working any more, but I can't reproduce that problem either... 😞

**Comment by maniackcrudelis** [comment]
Oh, it's quite old.
I can't remember what I've done before.
But, probably nothing, I think it was just a quick install on a VM.
Let's retry that ;)

**Comment by maniackcrudelis** [comment]
Hum that's strange... I can't reproduce it anymore.
I tried from the current stable (in official list) and from the current testing, there's no problem with the login. With and without the sso.

**Pull request merged**
