### PR TITLE
move the nextcloud log file to /var/log

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- people absolutely wants to edit the fail2ban config because they moved their data_dir elsewhere
see: https://github.com/YunoHost/doc/pull/2415 https://github.com/YunoHost/doc/pull/2416

## Solution

- move the log file to `/var/log`, where it belongs, so no need to change that damn fail2ban file at all 😓

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by ericgaspar** [comment]
shall we also remove logs `ynh_secure_remove --file="/var/log/$app"` in remove script?

**Comment by OniriCorpe** [comment]
> shall we also remove logs `ynh_secure_remove --file="/var/log/$app"` in remove script?

yeah why not

**Comment by OniriCorpe** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by niko2** [comment]
This will also help for logrotate that needs to be updated when data_dir is changed

**Comment by OniriCorpe** [comment]
that's the whole point 😅😅😅😅😅

**Pull request merged**
