### PR TITLE
23.0.2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
@kay0u Do you have any clue what the upgrade error is about?

**Comment by kay0u** [comment]
> @kay0u Do you have any clue what the upgrade error is about?

After digging the error, packages `php-apcu php-igbinary php-imagick php-redis` are installed (when we want `php7.3-apcu php7.3-igbinary php7.3-imagick php7.3-redis`), which break the upgrade, I'm not sure to understand why.

**Comment by kay0u** [comment]
Logs from package_check install:

https://paste.yunohost.org/raw/qaqevoduka

Idk how to fix this to be honest

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by ericgaspar** [comment]
!testme

**Review by kay0u — APPROVED** [review]

**Pull request merged**
