### PR TITLE
23.0.0

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version 23.0.0
- Upgrade to PHP8.0 (version recommended in Nextcloud doc)
- Config-panel (the config panel needs more work)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/117)
[](https://ci.pijean.ovh/ci/job/117)

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by alexAubin** [comment]
>!tastemetitus

Wait, it's not a typo ?!? :star_struck:

**Pull request merged**
