### PR TITLE
Add a post_user_delete hook

### PR DESCRIPTION
**Pull request by Tagadda**
## Problem

- #572 

## Solution

- Create a hook that deletes users from the DB

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by oleole39** [comment]
Thanks a lot for this. I was working on the same point and at the point of forking the repo I notice your fresh PR.
I've tested manually your fix with the following process:
- add a test user
- grant it access to Nextcloud
- Associate an email account (the default associated YNH mail) to this Nextcloud account in Nextcloud Mail
- Log out from YNH SSO & Nextcloud
- Copying the new hook file (the one you created with this PR) in the hooks' app folder.
- restart YNH server (just in case)
- go to YNH admin panel and delete the test user account
- `sudo -u nextcloud php8.1 --define apc.enable_cli=1 occ user:list` shows the user is deleted (although for some reason the same result was already reached without the new hook)
- check the table `oc_mail_accounts` in nextcloud MySQL database, the deleted user's mail account info are still there.  

Probably additional commands such as `occ mail:account:delete` (to delete the account) and `mail:clean-up` (to remove data related to it) needs to be run in the hook (cf. https://help.nextcloud.com/t/how-to-have-nextcloud-mail-stop-retrieving-emails-for-an-account-which-was-not-fully-removed/162587/2). I wonder if this can be considered as a Nextcloud bug (or Nextcloud apps bug) - should user:delete delete all data associated to the user in all Nextcloud apps?

**Comment by Tagadda** [comment]
> Copying the new hook file (the one you created with this PR) in the hooks' app folder.

Where did you copy it to ? "app folder" sounds like `/etc/yunohost/apps/nextcloud/hooks/`, but that's not correct. Hooks live at `/etc/yunohost/hooks.d/` (cf. [documentation](https://yunohost.org/en/packaging_apps_hooks#how-to-add-a-custom-hook-))
Here, you'll need to copy this hook to `/etc/yunohost/hooks.d/post_user_delete/50-nextcloud`

Anyway, I tested this PR and the table `oc_mail_accounts` is empty after I removed the user :rocket:

**Comment by oleole39** [comment]
That was indeed my mistake. I did a new test with the file in folder you indicate and it works very well.
Just noticing that it still doesn't delete the reference to "testuser" in the following tables (probably not a big deal though):
- `oc_addressbookchanges` (would it remain here for compatibility issue for remaining users - to keep seeing that a user of that name existed at some point?) 
- `oc_jobs` (jobs history, no need to delete)
- `oc_mail_tags` (not sure why it remains here)
- `oc_notifications_settings` (not sure why it remains here)
- `oc_storages` (not sure why it remains here)

**Comment by oleole39** [comment]
> Just noticing that it still doesn't delete the reference to "testuser" in the following tables (probably not a big deal though):

It could apparently be related to Nextcloud (Server part and Mail & Notifications apps) more than to the Yunohost package.
https://github.com/nextcloud/server/issues/38680
https://github.com/nextcloud/notifications/issues/1572

**Comment by oleole39** [comment]
> It could apparently be related to Nextcloud (Server part and Mail & Notifications apps) more than to the Yunohost package. [nextcloud/server#38680](https://github.com/nextcloud/server/issues/38680) [nextcloud/notifications#1572](https://github.com/nextcloud/notifications/issues/1572)

- removal of user data in `oc_notifications_settings` has been solved upstream: https://github.com/nextcloud/notifications/issues/1572

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
any thoughts. shall we merge this?

**Review by alexAubin — APPROVED** [review]

**Pull request merged**
