### PR TITLE
Upgrade to nextcloud  12.0.1

### PR DESCRIPTION
**Pull request by Rafi594**
## Problems
Apply minor upstream update 12.0.1

## Solution
Change version versions (readme, manifest) and upstream archive link.

## PR Status
Work finished.
Could be reviewed and tested.

## Validation

- [X] Complete test : Maniack C
- [X] Upgrade previous version : Maniack C
- [X] Code review : JimboJoe
- [X] Approval (LGTM) : JimboJoe
- [x] Approval (LGTM) : frju365
- [X] CI succeeded : JimboJoe

[Minor decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization.md#minor-decision)

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Test an upgrade from the current version 12.0.0
And check the app after that.
All is good.

**Comment by frju365** [comment]
LGTM : ok !

**Comment by maniackcrudelis** [comment]
Can be merged in 3 days

**Comment by frju365** [comment]
Let's merge it !

**Pull request merged**
