### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *nextcloud is vulnerable to path traversal issues*
- *this package could benefit from fail2ban*

## Solution
- *fix nginx configuration to protect from path traversal issue*
- *add fail2ban configuration*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR184/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Let's review this testing before releasing it (good feedback on the forum).
Then we can move on with a 15.0.7 testing.

**Comment by maniackcrudelis** [comment]
Do we know what happened with https://github.com/YunoHost-Apps/nextcloud_ynh/issues/195 ? Will this testing fix that behavior ?

**Comment by JimboJoe** [comment]
I just don't know...

**Comment by JimboJoe** [comment]
Didn't get time to look more into this... shall be release it, based on positive feedbacks on the forum? Anyone will to test more?
[15.0.7](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/194) (and soon 16!) is waiting behind...

**Comment by lapineige** [comment]
Just tested it: upgrade works fine, fail2ban too.

**Comment by JimboJoe** [comment]
Backup/restore failed in the CI (!!)
```
Warning: yunohost.hook <lambda> - [949.1] mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `oc_filecache` at row: 0
Warning: yunohost.hook <lambda> - [949.1] !!
Warning: yunohost.hook <lambda> - [949.1]   nextcloud's script has encountered an error. Its execution was cancelled.
Warning: yunohost.hook <lambda> - [949.1] !!
```
Relaunching to see if it's reproducible...

**Comment by maniackcrudelis** [comment]
> I can't relaunch it, I think I don't have credentials for ci-apps-hq...

The password for the user 'ynhci' is the same for all CI.

**Comment by JimboJoe** [comment]
Then I've always missed that login/password... :blush:

**Comment by JimboJoe** [comment]
OK, so the CI test OK, I'm proposing to release that stable today, if nobody's opposed to it.

**Pull request merged**
