### PR TITLE
Fix packages dependencies

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *php7.3-apcu does not exist, only php-apcu*

## Solution
- *Install php-apcu instead.*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/nextcloud_ynh%20PR289/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by alexAubin** [comment]
Are you sure about that ? A few minutes ago I'm helping someone on the chat about a similar thing ...

>Alaiks : what if you try to install manually "apt install ? php7.3{bz2,imap,smbclient,gmp,apcu,redis,zip,igbinary}" 
>User: I get this error
```
 Package php7.3-apcu is a virtual package provided by:
php-apcu 5.1.18+4.0.11-1+0~20191219.13+debian9~1.gbpa99079 [Not candidate version]  
```

So to me it's less about php7.3-acpu not existing rather than this : 

>Aleks: what does "apt policy php-acpu" says ?
>User:
```
php-apcu:
Installed: (none) 
Candidate: (none)
Version table:
5.1.18+4.0.11-1+0~20191219.13+debian9~1.gbpa99079 -30000 
 990 https://packages.sury.org/php stretch/main amd64 Packages
5.1.8+4.0.11-1 -30000
 990 https://deb.debian.org/debian stretch/main amd64 Packages   
```

Note the wtf -30000 for the version that should be candidate

And apparently related to some bug detected by the maintainer or idk ? (In italian during apt install ) : 

```
Recupero delle segnalazioni di bug... Fatto
Analisi delle informazioni... Fatto
Bug serious di php-apcu (→ 5.1.18+4.0.11-1+0~20191219.13+debian9~1.gbpa99079) <Aperti>
 b1 - #953777 - php-apcu breaks php-doctrine-cache autopkgtest: Class 'DOMDocument' not found
Riepilogo:
 php-apcu(1 bug)
Installare/aggiornare i precedenti pacchetti? [Y/n/?/...]
```

**Comment by maniackcrudelis** [comment]
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=php-apcu
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=php7.3-apcu
I just had a look at this and actually that package doesn't exist

**Comment by zamentur** [comment]
It exists on sury but not on buster, maybe ?

**Comment by alexAubin** [comment]
Closing because it's been a year and apparently no confirmation that this is an actual issue

**Pull request closed without merging**
