### PR TITLE
Added the  "php-ldap" dependency

### PR DESCRIPTION
**Pull request by anmol26s**
## Problem
- *Issue https://github.com/YunoHost-Apps/nextcloud_ynh/issues/69* 
```
Warning:   [Exception]
Warning:   App "LDAP user and group backend" cannot be installed because the following dependencies are not fulfilled: The library ldap is not available.
```
Dependency not installed : LDAP plugin of PHP.

## Solution
- *Install missing dependencies "php-ldap"*

## PR Status
To be reviewed. 

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR71%20(Official_fork)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by frju365** [comment]
Nice ! Thanks for your work !

**Comment by maniackcrudelis** [comment]
This package isn't available on jessie.
https://packages.debian.org/search?keywords=php-ldap&searchon=names&suite=all&section=all&sourceid=mozilla-search

**Comment by anmol26s** [comment]
Hmm...I have php7 installed became of Monica package.

**Comment by frju365** [comment]
For this PR, if you change the dependency to php5-ldap, it will work.

**Comment by frju365** [comment]
@maniackcrudelis , @JimboJoe  : Is it ok like that ?

**Comment by maniackcrudelis** [comment]
Upgrade ok, LGTM.

Will be merged in 3 days.

**Pull request merged**
