### PR TITLE
Update to nextcloud 12 (closes #36 and #38)

### LINKED ISSUE #36: NC 12 is out !
Hi, 

Nextcloud 12 is out today. It includes a js script loader app, which could help solving
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/26

Happy to test beta if needed

### PR DESCRIPTION
**Pull request by Rafi594**
- [X] Complete test : JimboJoe
- [X] Upgrade previous version : JimboJoe
- [X] Code review : JimboJoe
- [X] Approval (LGTM) frju365
- [X] Approval (LGTM) : Maniack C
- [x] CI succeeded : JimboJoe

[Minor decision](https://github.com/YunoHost/project-organization/blob/master/yunohost_project_organization.md#minor-decision), closed on June 21st, or June 17th if anticipated.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Nextcloud can't work only with this kind of upgrade, because nextcloud can't jump any major version.
So you need to add a upgrade script in upgrade.d, like this script
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade.d/upgrade.10.sh

**Comment by Rafi594** [comment]
It is right

**Comment by JimboJoe** [comment]
Hi @Rafi594, thanks for your PR!
I've just invited you to the Github YunoHost-Apps organization so that you can interact more easily next time you want to propose a PR for Nextcloud (just create a branch in the nextcloud_ynh upstream repository) ;-)
I'll have look at your PR.

**Comment by maniackcrudelis** [comment]
Your script upgrade.11.sh need a execution right.
For the moment, your branch doesn't work.

**Comment by JimboJoe** [comment]
I first needed to set +x on `upgrade.11.sh`, and the next error when upgrading from 11.0.3 is (extract from the complete log): 
```
+ ./upgrade.d/upgrade.11.sh
Warning:
Warning: Update to nextcloud 12.0.0
Warning: tar: /tmp/tmp.WGweh8okMV: Cannot open: Permission denied
Warning: tar: Error is not recoverable: exiting now
```

**Comment by Rafi594** [comment]
I have tested chmod +x /upgrade.d/upgrade.11.sh but it don't work

Warning: chmod: cannot access ‘/upgrade.d/upgrade.11.sh’: No such file or directory

Thanks for you for your help

3 juin 2017 10:07 "JimboJoe"  a écrit:
	I first needed to set +x on upgrade.11.sh, and the next error when upgrading from 11.0.3 is (extract from the complete log): 

	+ ./upgrade.d/upgrade.11.sh Warning: Warning: Update to nextcloud 12.0.0 Warning: tar: /tmp/tmp.WGweh8okMV: Cannot open: Permission denied Warning: tar: Error is not recoverable: exiting now

**Comment by maniackcrudelis** [comment]
You have to do the chmod +x from your local copy of this repository. You can't do that with github.
And we can't do that for you, because we don't have any right access on your repository.

**Comment by Rafi594** [comment]
Its good for me

**Comment by maniackcrudelis** [comment]
It's ok, your commit is on your branch, and so on this PR.

**Comment by JimboJoe** [comment]
Sorry, I had created a Nextcloud team, but forgot to give it write access on nextcloud_ynh... fixed now!
Great you overcame the rights problem in the repository 👍 

Unfortunately, I still get the second error related above.
You'll find the complete log [here](https://paste.yunohost.org/wevacetasa.diff)
It seems related in some way to [that fix](https://github.com/YunoHost-Apps/nextcloud_ynh/commit/89a336801f7452b9037f6409f095ef5ef9efcb77) I had come with, but that I finally reverted (and I don't remember why...). @maniackcrudelis what do you think?

**Comment by JimboJoe** [comment]
OK, my problems are due to the fact that my server are running the testing branch...
So to keep the package working when the current testing gets stable, we need to fix that.
@Rafi594 Could you please implement this [small patch](https://github.com/YunoHost-Apps/nextcloud_ynh/commit/89a336801f7452b9037f6409f095ef5ef9efcb77) in you PR?

**Comment by JimboJoe** [comment]
That worked a treat on my VM server! 👍 

Unfortunately I got another error during my production server upgrade (see complete log [here](https://paste.yunohost.org/ixuzerucam.diff)).
Relevant log extract:
```
Attention : Update to nextcloud 12.0.0
patching file core/Controller/LoginController.php
Hunk #1 succeeded at 107 (offset 7 lines).
Maintenance mode enabled
Delete directory /var/www/nextcloud
Attention : PHP Fatal error:  Class '\OC\Memcache\APC' not found in /var/www/nextcloud/lib/private/Memcache/Factory.php on line 116
Attention : PHP Fatal error:  Class '\OC\Memcache\APC' not found in /var/www/nextcloud/lib/private/Memcache/Factory.php on line 116
Attention : Unable to upgrade Nextcloud
```

The server was in 11.0.2, so I tried upgrading it to 11.0.3 beforehand, but got the same error.

**Comment by Rafi594** [comment]
It maybe the error in the nextcloud administration

**Comment by JimboJoe** [comment]
Can't be related to the warning in the administration panel; it's a run-time error in nextcloud CLI execution [here](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade.d/upgrade.generic.sh#L48)... I don't see what difference that server could have to make that fail :-/

**Comment by JimboJoe** [comment]
OK I've found the issue: I had the line `memcache.locking": "\\OC\\Memcache\\APC",` in my config.php.
Funny enough, I haven't found this parameter in any version of ownCloud or Nextcloud package, and don't seem to remember why it could have ended up in my configuration file :-)
So after removing that setting, everything's fine!

**Comment by JimboJoe** [comment]
Can you possible handle this performance tuning?
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/server_tuning.html#enable-php-opcache

**Comment by JimboJoe** [comment]
Excellent! So we now just lack this:
```
L'en-tête HTTP "X-Frame-Options" n'est pas configurée pour être égale à "SAMEORIGIN" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est recommandé d'ajuster ce paramètre.
```
I don't know who can help us on that point...

**Comment by JimboJoe** [comment]
For your information, I get numerous logs like this in /home/yunohost.app/nextcloud/data/nextcloud.log and /var/log/php5-fpm.log
```
Zend OPcache can't be temporary enabled (it may be only disabled till the end of request)
```

I don't know if it's related to [this](https://ma.ttias.be/php-warning-zend-opcache-cant-temporary-enabled/)

**Comment by JimboJoe** [comment]
Unfortunately it doesn't seem to change anything for me... :-(

**Comment by JimboJoe** [comment]
Still not better... Do you reproduce my warnings on your instance...?

**Comment by Rafi594** [comment]
Yes I have the same problem on my instance

`	Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0`

**Comment by JimboJoe** [comment]
Still not better on my side... Was it better on yours?

**Comment by Rafi594** [comment]
I have no problem just the error in the log

10 juin 2017 19:38 "JimboJoe"  a écrit:
	Still not better on my side... Was it better on yours?

**Comment by JimboJoe** [comment]
I get your point, but in my opinion, any warning message that we can't explain is a really BAD thing, and we can't let it as-is for an official app ;-)
I tried removing your parameters in the nextcloud.conf and creating by hand a `/etc/php5/fpm/conf.d/20-nextcloud.ini` with the [recommended parameters](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/server_tuning.html#enable-php-opcache). It seems perfectly fine for me now... do you confirm?
If that's OK, could you possible implement the ini file creation (ideally with [this helper](https://github.com/YunoHost/yunohost/pull/284) to be pasted in `_common.sh`)? I've used it successfully in [Wallabag2](https://github.com/YunoHost-Apps/wallabag2_ynh).
Thanks!

**Comment by Rafi594** [comment]
Yes it work fine with this modification. I will look for the script

**Comment by Rafi594** [comment]
I will test it later

**Comment by Rafi594** [comment]
It doesn't work can you help me

**Comment by Rafi594** [comment]
Warning: ./_common.sh: line 203: final_path: unbound variable

**Comment by Rafi594** [comment]
Its ok
The problem
L'en-tête HTTP "X-Frame-Options" n'est pas configurée pour être égale à "SAMEORIGIN" créant potentiellement un risque relié à la sécurité et à la vie privée. Il est recommandé d'ajuster ce paramètre.

**Comment by ewilly** [comment]
Hello,
according to 

> https://github.com/nextcloud/vm/blob/master/static/setup_secure_permissions_nextcloud.sh

 the permissons could be enforced to more security. Could this pull request include this ?

**Comment by JimboJoe** [comment]
OK, I finally found the reason for the remaining warning about X-Frame-Options: if you look into the [release notes](https://docs.nextcloud.com/server/12/admin_manual/release_notes.html#updates-to-nginx-configuration), it explicitly asks to remove the `add_header X-Frame-Options "SAMEORIGIN";` from the nginx configuration file (it's now managed directly in PHP).

**Comment by Rafi594** [comment]
Fixed

**Comment by JimboJoe** [comment]
Oh I see I missed @ewilly 's comment, sorry for that!
@Rafi594 could you check you could take these slight right changes into account (if not already OK)?

**Comment by Bridouz** [comment]
Hi,

I don't know if you could do something about it but with NC 12 some apps (like news) are starting to throw errors about non-UTF8 in DB tables.

The problem is known from NC and can ne fixed by following this :

https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by Rafi594** [comment]
Hi

When we merge it ?

**Comment by JimboJoe** [comment]
I resolved the merge conflict.
I created issues #47 and #48 to look into @ewilly and @Bridouz suggestions an a later PR.
So... this PR seems ready to merge (thanks to @Rafi594)!

It will be merged in 3 days if no further commits/comments.

**Pull request merged**
