### PR TITLE
[enh] Add change_url

### LINKED ISSUE #51: Add change_url script
In order for this application to allow to change the URL via the `yunohost app change-url` command (available since YunoHost 2.6), the `change_url` script must be created.

### PR DESCRIPTION
**Pull request by Rafi594**
## Problem
- *Issue https://github.com/YunoHost-Apps/nextcloud_ynh/issues/51* 
Possibility to change the URL of the application after installation.

## Solution
- *Add the change_url script*

## PR Status
Could be reviewed and tested.
fixes #51 

## Validation
---
*Minor decision*
- [ ] **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** :  
- [ ] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR67%20(Official_fork)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
I guess there's something to do about [this](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/config.json#L6).

**Comment by Rafi594** [comment]
Fixed

**Comment by maniackcrudelis** [comment]
It failed in my test

```
Change the url from sous.domain.tld/ to sous.domain.tld/path...
Change_url script successful. (0)
Warning: yunohost.hook <lambda> - [1029.1] sed: impossible de lire : Aucun fichier ou dossier de ce type
Warning: yunohost.hook <lambda> - [1029.1] md5sum: : Aucun fichier ou dossier de ce type                                                    

Try to access by url...
Public access forced by a skipped_uris to check.
Test url: sous.domain.tld/path
Real url: https://domain.tld/yunohost/sso/?r=aHR0cDovL3NvdXMuZG9tYWluLnRsZC9pbmRleC5waHAvcGF0aA==                                           
HTTP code: 200                                                                                                                              
Title of the page: YunoHost Portal                                                                                                          
The connection attempt fall on the YunoHost portal.
Test url: sous.domain.tld/path/                                                                                                             
Real url: https://domain.tld/yunohost/sso/?r=aHR0cDovL3NvdXMuZG9tYWluLnRsZC9pbmRleC5waHAvcGF0aC8=                                           
HTTP code: 200                                                                                                                              
Title of the page: YunoHost Portal                                                                                                          
The connection attempt fall on the YunoHost portal.
--- FAIL ---
```

**Comment by maniackcrudelis** [comment]
CI [failed](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR67%20(Official_fork)/2/consoleFull) on Change URL tests.

**Comment by Rafi594** [comment]
I'll work on it this afternoon

**Comment by maniackcrudelis** [comment]
I moved this branch to https://github.com/YunoHost-Apps/nextcloud_ynh/tree/add_change_url, the name of this branch break the CI. Which is already capricious enough !

**Pull request closed without merging**
