### PR TITLE
Testing

### LINKED ISSUE #138: nextcloud is leaking specific php configuration globally
The content of conf/php-fpm.ini is installed to fpm/conf.d making the options available to all fpm pools.
The correct way to set php options for a specific pool is to set them in the pool.d/{{app}}.conf file

I noticed this after a stretch migration, where the specific files in conf.d from php5 are not copied over to the equivalent php7 dir. Thus nextcloud complained about unoptimized php settings after the migration (in settings/Administration/Basic Settings/Security & setup warnings).

Manually adding :
```
php_value[opcache.enable]=1
php_value[opcache.enable_cli]=1
php_value[opcache.interned_strings_buffer]=8
php_value[opcache.max_accelerated_files]=10000
php_value[opcache.memory_consumption]=128
php_value[opcache.save_comments]=1
php_value[opcache.revalidate_freq]=1
```
at the end of `/etc/php/7.0/fpm/pool.d/nextcloud.conf` fixes the warnings

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *This package isn't (at all) up-to-date with upstream*
- *Fix #138*
- *Some maintenance operations are needed after upgrade, otherwise warnings appear in Nextcloud administration overview*

## Solution
- *Upgrade to latest stable version*
- *Remove the php.ini file and integrate its content to the pool file
According to the ynh_add_fpm_config helper, the ini file is only processed if it exists.*
- *Apply recommended maintenance operations a little while after upgrade in order to let the upgrade finish and not block the upgrade process (these operations can last long on existing instances with already much data)*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20testing%20(Official)/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Oops! Looks we weren't finished with that testing before I merged 15.0.0 release... Let's move on anyway with that new testing... :blush:

**Comment by supermamie** [comment]
So we'll switch from 13 to 15 directly ?
Nice :slightly_smiling_face:

**Comment by frju365** [comment]
for me, I'm having an issue in upgrade on production server (from 14 to 15). I will investigate (perhpas just a case)

**Comment by frju365** [comment]
I've this error (just if you know already it : UnexpectedValueException: The files of the app "user_external" were not correctly replaced before running the update)

**Comment by JimboJoe** [comment]
Never seen that... seems related to a failed plugin ("app") upgrade... ??

**Comment by frju365** [comment]
Ok. It was an incompatible plugin : External user support. Without this plugin everything is ok, so I reapprove the PR :-), but I think either I open an issue for this plugin (maybe installed on some instances), or we let a message during the official release on the forum post, or we disable this plugin during upgrade.

**Comment by frju365** [comment]
Let's merge in two days (already yesterday). We will think about the warning about the plugin. I think a little announcement on the forum after the release is still ok ? Any opinion ?

**Comment by JimboJoe** [comment]
Well, provided:
* we released the testing only 2 days ago
* there are other pending PRs ([#157](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/157)... to be reviewed :wink: )
* there seem to still be problems on this testing (see forum [here](https://forum.yunohost.org/t/official-app-nextcloud/4104/129))
... then let's wait a bit until everything settles :wink:

**Comment by alexAubin** [comment]
Bumpz ? :s

**Comment by supermamie** [comment]
I just updated my server and I have those 2 lines of warning

> -  L'utilisation de la fonctionnalité d'envoi d'e-mails native de PHP n'est plus supportée. Merci de mettre à jour les paramètres d'envoi d'e-mails de votre serveur ↗
> -  Vous utilisez actuellement PHP 7.0.33-0+deb9u1. Mettez à jour votre version de PHP afin de tirer avantage des améliorations liées à la performance et la sécurité fournies par le PHP Group dès que votre distribution le supportera.

**Comment by alexAubin** [comment]
Tried it on my server : 
- I have the same warning about PHP 7.0.33, but I doubt we can do anything about it, it's about PHP packagin in Debian I guess ? Doesn't sounds like a big deal also.
- I don't have the warning about email ... Not sure what it's about but anyway sounds like something that doesn't break Nextcloud ultimately..

Soooo, to me that looks good :wink: No pressure but would be nice if we can merge this in the coming days, people are waiting for this :stuck_out_tongue_winking_eye:

**Comment by JimboJoe** [comment]
I'm also in favor of merging this quickly, as we got excellent feedbacks on the forum the past few days
ping @YunoHost-Apps/apps-group  :wink:

**Comment by Mickael-Martin** [comment]
I can try to upgrade my instance (33k files) to testing if you want. 
I want to patch it to 13.0.11 today or tomorrow...

**Comment by JimboJoe** [comment]
Well, that could prove useful (and I think we're quite ready for a stable release)! :+1:

**Comment by maniackcrudelis** [comment]
Agree to merge in 3 days, if the CI agrees too ;)

**Comment by Mickael-Martin** [comment]
I try to update to 13.0.11 but any action with chown or chmod on my datadir take 1 hour (samba remote dir with 33k files). Can I propose a fix with a find -exec (only 10 minutes by action) ?

**Comment by JimboJoe** [comment]
That looks promising, please feel free to to so! :+1:

**Comment by Mickael-Martin** [comment]
OK, after some tests on 4k files : 
chown/chmod all is faster (around 0s) than find method (<1s) on a local storage.
chown/chmod all is slower (5m30) than find method (42s) on a remote storage.

Anyone to make another test on local storage ?

**Comment by Mickael-Martin** [comment]
With local storage : 
without patch
real	2m18,940s
user	1m8,096s
sys	0m18,924s

with patch
real	2m15,848s
user	1m6,748s
sys	0m18,848s

With remote storage (my personnal instance): 
without patch :
fork: Cannot allocate memory after 45min

with patch :
sudo -u nextcloud php occ --no-interaction --no-ansi upgrade 
DEBUG An unhandled exception has been thrown: 
WARNING Unable to upgrade Nextcloud 
DEBUG TypeError: Argument 4 passed to OCA\Theming\ThemingDefaults::__construct() must implement interface OCP\Files\IAppData, instance of OC\
Memcache\Factory given, called in /var/www/nextcloud/lib/private/Server.php on line 952 and defined in /var/www/nextcloud/apps/theming/lib/ThemingDefaults.php:93
after 26 minutes (with automatic restoration).
I lookup the bug.

**Comment by Mickael-Martin** [comment]
Another bug after disabling theme app :
```
sudo -u nextcloud php occ --no-interaction --no-ansi upgrade
DEBUG Nextcloud or one of the apps require upgrade - only a limited number of commands are available
DEBUG You may use your browser or the occ upgrade command to do the upgrade
DEBUG Set log level to debug
DEBUG Turned on maintenance mode
DEBUG Updating database schema
DEBUG Updated database
DEBUG UnexpectedValueException: The files of the app "files" were not correctly replaced before running the update
DEBUG Update failed
DEBUG Maintenance mode is kept active
DEBUG Reset log level
```

**Comment by Mickael-Martin** [comment]
For me, If you have one or more apps with appinfo with version specification lower than upgrade (14 for me at this time), you cannot upgrade the instance. Yunohost script cannot actually upgrade mine.
```
grep min-version /var/www/nextcloud/apps/activity/appinfo/info.xml 
		<nextcloud min-version="13" max-version="13" />
```
Maybe the use of updater.phar (with app upgrade) is more efficient for my case.

**Comment by Mickael-Martin** [comment]
OK, upgrade passed my patch. But :
- I had disable "all" my nextcloud apps and re-enable after upgrade process
- I have warning about X- headers (duplicate headers make warning on setting page)

**Comment by JimboJoe** [comment]
@Mickael-Martin thanks for your tests!
Can you please open an issue with that information, or ideally a PR...?
I'll merge this testing to have a stable release, but we can go on working on your problems/suggestions.

**Comment by alexAubin** [comment]
Oh yis :tada: :balloon:

**Comment by alexAubin** [comment]
>I've this error (just if you know already it : UnexpectedValueException: The files of the app "user_external" were not correctly replaced before running the update)

Turns out some user do have this plugin and upgrade failed for them :/

**Pull request merged**
