### PR TITLE
Testing

### LINKED ISSUE #317: Keeweb doesn't work
I've installed nextcloud-keeweb on my nextcloud, but the app doesn't work at all.

Here is a screenshot of how it renders: 

I've talked about this issue on https://github.com/jhass/nextcloud-keeweb/issues/143#issuecomment-641130673

Several yunohost users are getting a similar problem. I've installed nextcloud on my computer just to try, then nextcloud-keeweb, and it works as expected.

I've seen this issue: https://github.com/YunoHost-Apps/nextcloud_ynh/issues/161 and I've tried the commands, but it's not better.

Do you have any clue?

### LINKED ISSUE #331: Element (Riotchat) doesn't work
Everything is explained in this thread : https://github.com/gary-kim/riotchat/issues/26

Installations works without problem, but when we go to the app, nothing appears.

Someone who tried to dig the issue said : 

> So, the issue seems to be that when loading Riot, the requests for the static resources are being redirected to the login page by Yunohost. I don't know why that is but it seems like it's happening to quite a few of the requests. I think this would be an upstream issue in Yunohost. Gonna try debugging a little further.

### LINKED ISSUE #345: Scan files fails due to symlink not followed
Hello team,

Since https://github.com/nextcloud/server/issues/20592, the NextCloud file scan does not follow symlinks. I'm pretty sure that there is a YNH workaround, yet my %USER%/Multimedia is borken after manual update "Forbidden operation"

Either there is a wrapped (yet unknown to myself) command to update, or there is a bug ? This is blocking my prod instance as my multimedia files disappeared.

Intended : 
`# sudo -su nextcloud php7.3 /var/www/nextcloud/occ files:scan MYUSER`

Expected : 
All files scanned. MYUSER files available from WebUI.

Got:
```
Starting scan for user 1 out of 1 (MYUSER)
Exception during scan: Following symlinks is not allowed
#0 /var/www/nextcloud/lib/private/Files/Storage/Local.php(161): OC\Files\Storage\Local->getSourcePath('/Share')
#1 /var/www/nextcloud/lib/private/Files/Storage/Common.php(884): OC\Files\Storage\Local->getMetaData('/Share')
#2 [internal function]: OC\Files\Storage\Common->getDirectoryContent('')
#3 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(408): iterator_to_array(Object(Generator))
#4 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('', true, 3, 286839, true, 0)
#5 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren('', true, 3, 286839, true)
#6 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan('', true, 3)
#7 /var/www/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan('/kifof', true, NULL)
#8 /var/www/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles('kifof', '/kifof', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#16 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#17 {main}
```

Version: nextcloud 19.0.3~ynh1 from yunohost 4.0.8

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *New version upstream*
- *See bug #331*

## Solution
- *Upgrade to version 20.0.4*
- *Small typos*
- *Rework the nginx conf (close #331 close #332 close #317)*
- *Allow Symlinks (Fix #345)*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20PR346%20(Kay0u)/)  [pipeline status](https://git.kayou.io/kayou/nextcloud_ynh/-/commits/testing) 
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Reinstallation after root installation keeps failing on the CI... :thinking:

**Comment by JimboJoe** [comment]
```
{"reqId":"rpREof0n4jb49eDWlAGy","level":3,"time":"2020-11-01T08:41:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"file_put_contents(): Only 0 of 542 bytes written, possibly out of free disk space at /var/www/nextcloud/lib/private/Setup.php#596","Code":0,"Trace":[{"function":"onError","class":"OC\LogrrorHandler","type":"::","args":[2,"file_put_contents(): Only 0 of 542 bytes written, possibly out of free disk space","/var/www/nextcloud/lib/private/Setup.php",596,
```
Could it be a CI disk saturation/quota exceeded...?

**Comment by kay0u** [comment]
Yes probably, I tried to fix it in several ways, but I was unsuccessful.

**Comment by JimboJoe** [comment]
Upgrade from 19.0.3 with mail app doesn't go well:

<details>
<summary>log extract</summary>

```
2020-11-17 19:21:36,546: DEBUG - Update app mail from appstore
2020-11-17 19:21:52,101: DEBUG - An unhandled exception has been thrown:
2020-11-17 19:21:52,101: WARNING -     0/0 [->--------------------------]   0%Unable to upgrade Nextcloud
2020-11-17 19:21:52,101: DEBUG - Error: Class 'OCA\Mail\AppInfo\BootstrapSingleton' not found in /var/www/nextcloud/apps/mail/lib/AppInfo/Application.php:35
2020-11-17 19:21:52,101: DEBUG - Stack trace:
2020-11-17 19:21:52,101: DEBUG - #0 /var/www/nextcloud/lib/private/ServerContainer.php(108): OCA\Mail\AppInfo\Application->__construct()
2020-11-17 19:21:52,102: DEBUG - #1 /var/www/nextcloud/lib/private/ServerContainer.php(171): OC\ServerContainer->getAppContainer('mail', 'Mail')
2020-11-17 19:21:52,102: DEBUG - #2 /var/www/nextcloud/lib/private/ServerContainer.php(138): OC\ServerContainer->getAppContainerForService('OCA\\Mail\\Migrat...')
2020-11-17 19:21:52,102: DEBUG - #3 /var/www/nextcloud/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query('OCA\\Mail\\Migrat...')
2020-11-17 19:21:52,102: DEBUG - #4 /var/www/nextcloud/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance('1050Date2020062...')
2020-11-17 19:21:52,102: DEBUG - #5 /var/www/nextcloud/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('1050Date2020062...', false)
2020-11-17 19:21:52,102: DEBUG - #6 /var/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\DB\MigrationService->migrate()
2020-11-17 19:21:52,102: DEBUG - #7 /var/www/nextcloud/lib/private/Installer.php(206): OC_App::updateApp('mail')
2020-11-17 19:21:52,102: DEBUG - #8 /var/www/nextcloud/lib/private/Updater.php(452): OC\Installer->updateAppstoreApp('mail')
2020-11-17 19:21:52,102: DEBUG - #9 /var/www/nextcloud/lib/private/Updater.php(260): OC\Updater->upgradeAppStoreApps(Array)
2020-11-17 19:21:52,103: DEBUG - #10 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.0.9', '19.0.3.1')
2020-11-17 19:21:52,103: DEBUG - #11 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
2020-11-17 19:21:52,103: DEBUG - #12 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-17 19:21:52,103: DEBUG - #13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-17 19:21:52,103: DEBUG - #14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-17 19:21:52,103: DEBUG - #15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-17 19:21:52,103: DEBUG - #16 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-17 19:21:52,103: DEBUG - #17 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
2020-11-17 19:21:52,103: DEBUG - #18 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```
</details>

Looks like a [known problem on the mail app](https://github.com/nextcloud/mail/issues/3727)

**Comment by JimboJoe** [comment]
I also can't seem to have the YunoHost tile appear, whether at domain root or in a subfolder. There's no sign of access in the nginx logs, so I guess it's something about nginx rules... ?

**Comment by ericgaspar** [comment]
I have updated to 20.0.4. When I go to `Fichiers`, I have this message .
`Ce répertoire est indisponnible, merci de consulter les journaux ou de contacter votre administrateur` and no file are displayed

**Comment by kay0u** [comment]
Crap, it was working with 20.0.0. Can you try to change the variable `$allowSymlinks` to `true` in the file `/var/www/nextcloud/lib/private/Files/Storage/Local.php` and confirm it fix the issue for you too? (I can reproduce, and I fixed it this way)

**Comment by ericgaspar** [comment]
> Crap, it was working with 20.0.0. Can you try to change the variable `$allowSymlinks` to `true` in the file `/var/www/nextcloud/lib/private/Files/Storage/Local.php` and confirm it fix the issue for you too? (I can reproduce, and I fixed it this way)

Ok it works now! 🎉

**Comment by ericgaspar** [comment]
I also have some warnings in **Avertissements de sécurité & configuration** section : 


Il manque des clés primaires dans la base de données. En raison du fait que l’ajout de clés primaires sur les grandes tables peut prendre un certain temps, elles n’ont pas été ajoutées automatiquement. En exécutant "occ db:add-missing-primary-keys", ces clés primaires manquantes peuvent être ajoutées manuellement pendant que l’instance continue de fonctionner.

    Clé primaire manquante sur la table "oc_federated_reshares".
    Clé primaire manquante sur la table "oc_systemtag_object_mapping".
    Clé primaire manquante sur la table "oc_comments_read_markers".
    Clé primaire manquante sur la table "oc_collres_resources".
    Clé primaire manquante sur la table "oc_collres_accesscache".
    Clé primaire manquante sur la table "oc_filecache_extended".

**Comment by kay0u** [comment]
Can you run `sudo -u nextcloud php7.3 /var/www/nextcloud/occ db:add-missing-primary-keys` please? :D

**Comment by ericgaspar** [comment]
> Can you run `sudo -u nextcloud php7.3 /var/www/nextcloud/occ db:add-missing-primary-keys` please? :D

✅ Tous les tests ont réussi.

Yes!

**Review by ericgaspar — APPROVED** [review]

**Comment by JimboJoe** [comment]
Upgrade unfortunately still fails if the mail app is installed and enabled...
Logs: https://paste.yunohost.org/raw/ovuwavokol
There is a corresponding (long standing) issue on the mail app issue tracker: https://github.com/nextcloud/mail/issues/3727

**Comment by kay0u** [comment]
> YunoHost tile is still absent

This should fix this issue: https://github.com/YunoHost/yunohost/pull/1113

> Upgrade unfortunately still fails if the mail app is installed and enabled...

I think we should disable this app before upgrading nextcloud, and enable it again right after. (I'm testing this right now and will create a PR if it works)

**Review by yalh76 — DISMISSED** [review]
Quick Review, LGTM

**Review by ericgaspar — APPROVED** [review]

**Comment by kay0u** [comment]
Now package check pass on my side (sorry for the noise before)

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
