### PR TITLE
24.0.4

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Installs flawlessly on Buster :+1:

**Comment by shedowe19** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!bullseyetestme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
Upgraded with zero issues on Bullseye !

**Review by kay0u — APPROVED** [review]

**Comment by adlmr** [comment]
Can't upgrade on Debian buster (without upgrading to Bullseye):
`yunohost app upgrade nextcloud
Info: Now upgrading nextcloud...
Error: Requirements are not met for nextcloud, the package yunohost (4.4.2.14) must be >= 11.0.9
`

**Pull request merged**
