### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Gallery plugin doesn't work for accounts containing many files (timeout)*
- *Optimize global performance*
- *We can't logout any more from Nextcloud and it doesn't logout from YunoHost any more.*
- *Upgrade script add another config at the end of logrotate config*
- *logrotate send an email every day: "error: nextcloud:37 duplicate log entry for /var/log/nextcloud/*.log"*
- *Package not up-to-date with upstream version*
- *Cron file isn't created with proper rights, thus preventing cron job to be run (issue #88).*
- *Settings are all overwritten at upgrade, whereas some settings could have been legitimately modified by the user (see [this forum post](https://forum.yunohost.org/t/official-app-nextcloud/4104/14?u=jimbojoe))*

## Solution
- *Add ImageMagick dependency and tune timeouts for Gallery plugin*
- *For optimization reason, and as Redis is already running on a YunoHost instance, setup Nextcloud to use it by default (see documentation [here](https://docs.nextcloud.com/server/12.0/admin_manual/configuration_server/caching_configuration.html#small-organization-single-server-setup) and recommendation for Gallery plugin [here](https://github.com/nextcloud/gallery/wiki/Requirements#recommended)).*
- *During global refactoring, existing patches haven't been moved to the right folder and they didn't respect the right naming scheme. Let's fix that!*
- *Use --non-append option*
- *Upgrade to uptream version 12.0.5*
- *fix cron config file rights*
- *separate settings for installation from settings that can be overwritten at upgrade.*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/nextcloud_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready to be reviewed

**Comment by maniackcrudelis** [comment]
Upgrade and Code review OK. LGTM

**Comment by frju365** [comment]
Waiting for CI build. And then, will be merged in 3 day.

**Comment by frju365** [comment]
OK, let's merge it !

**Pull request merged**
