### PR TITLE
added readme_fr.md

### PR DESCRIPTION
**Pull request by Saimyx**
I have translated the readme file in french :)

### CODE REVIEW

**Comment by Tagadda** [comment]
This conflicts with https://github.com/YunoHost-Apps/nextcloud_ynh/pull/278

**Comment by lapineige** [comment]
I've send a PR to fix this. @Saimyx please merge it, then we will be able to merge both #278 and this PR together :)

**Comment by maniackcrudelis** [comment]
Will merge in 3 days.

**Comment by maniackcrudelis** [comment]
If that PR is ready for you guys, I merge.

**Comment by lapineige** [comment]
Go for it :)

**Pull request merged**
